<a href="https://colab.research.google.com/github/lyadav44/data690_fall22/blob/main/Assignment_5/Lecture_7_Reading_Data_other_sources.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LESSON 1

In [ ]:
import pandas as pd

In [ ]:
filepath = 'btc-market-price.csv'

with open(filepath, 'r') as reader:
    print(reader)

<_io.TextIOWrapper name='btc-market-price.csv' mode='r' encoding='UTF-8'>

In [ ]:
filepath = 'btc-market-price.csv'

with open(filepath, 'r') as reader:
    for index, line in enumerate(reader.readlines()):
        # read just the first 10 lines
        if (index < 10):
            print(index, line)

0 2/4/17 0:00,1099.169125

1 3/4/17 0:00,1141.813

2 4/4/17 0:00,?

3 5/4/17 0:00,1133.079314

4 6/4/17 0:00,-

5 7/4/17 0:00,-

6 8/4/17 0:00,1181.149838

7 9/4/17 0:00,1208.8005

8 10/4/17 0:00,1207.744875

9 11/4/17 0:00,1226.617038

In [ ]:
csv_url = "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv"

pd.read_csv(csv_url).head()

  Country Name Country Code  Year         Value
0   Arab World          ARB  1968  2.576068e+10
1   Arab World          ARB  1969  2.843420e+10
2   Arab World          ARB  1970  3.138550e+10
3   Arab World          ARB  1971  3.642691e+10
4   Arab World          ARB  1972  4.331606e+10

In [ ]:
df = pd.read_csv('btc-market-price.csv')

df.head()

   2/4/17 0:00  1099.169125
0  3/4/17 0:00     1141.813
1  4/4/17 0:00            ?
2  5/4/17 0:00  1133.079314
3  6/4/17 0:00            -
4  7/4/17 0:00            -

In [ ]:
df = pd.read_csv('btc-market-price.csv',
                 header=None)

df.head()

             0            1
0  2/4/17 0:00  1099.169125
1  3/4/17 0:00     1141.813
2  4/4/17 0:00            ?
3  5/4/17 0:00  1133.079314
4  6/4/17 0:00            -

In [ ]:
df = pd.read_csv('btc-market-price.csv',
                 header=None,
                 na_values=['', '?', '-'])

In [ ]:
df.head()

             0            1
0  2/4/17 0:00  1099.169125
1  3/4/17 0:00  1141.813000
2  4/4/17 0:00          NaN
3  5/4/17 0:00  1133.079314
4  6/4/17 0:00          NaN

In [ ]:
df = pd.read_csv('btc-market-price.csv',
                 header=None,
                 na_values=['', '?', '-'],
                 names=['Timestamp', 'Price'])

In [ ]:
df.head()

     Timestamp        Price
0  2/4/17 0:00  1099.169125
1  3/4/17 0:00  1141.813000
2  4/4/17 0:00          NaN
3  5/4/17 0:00  1133.079314
4  6/4/17 0:00          NaN

In [ ]:
df = pd.read_csv('btc-market-price.csv',
                 header=None,
                 na_values=['', '?', '-'],
                 names=['Timestamp', 'Price'],
                 dtype={'Price': 'float'})

df.head()

     Timestamp        Price
0  2/4/17 0:00  1099.169125
1  3/4/17 0:00  1141.813000
2  4/4/17 0:00          NaN
3  5/4/17 0:00  1133.079314
4  6/4/17 0:00          NaN

In [ ]:
df.dtypes

Timestamp     object
Price        float64
dtype: object

In [ ]:
pd.to_datetime(df['Timestamp']).head()

0   2017-02-04
1   2017-03-04
2   2017-04-04
3   2017-05-04
4   2017-06-04
Name: Timestamp, dtype: datetime64[ns]

In [ ]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

df.head()

df.dtypes

Timestamp    datetime64[ns]
Price               float64
dtype: object

In [ ]:
df = pd.read_csv('btc-market-price.csv',
                 header=None,
                 na_values=['', '?', '-'],
                 names=['Timestamp', 'Price'],
                 dtype={'Price': 'float'},
                 parse_dates=[0])

df.head()

   Timestamp        Price
0 2017-02-04  1099.169125
1 2017-03-04  1141.813000
2 2017-04-04          NaN
3 2017-05-04  1133.079314
4 2017-06-04          NaN

In [ ]:
df.dtypes

Timestamp    datetime64[ns]
Price               float64
dtype: object

In [ ]:
df = pd.read_csv('btc-market-price.csv',
                 header=None,
                 na_values=['', '?', '-'],
                 names=['Timestamp', 'Price'],
                 dtype={'Price': 'float'},
                 parse_dates=[0],
                 index_col=[0])
df.head()

                  Price
Timestamp
2017-02-04  1099.169125
2017-03-04  1141.813000
2017-04-04          NaN
2017-05-04  1133.079314
2017-06-04          NaN

In [ ]:
df.dtypes

Price    float64
dtype: object

In [ ]:
exam_df = pd.read_csv('exam_review.csv')
exam_df

                               first_name>last_name>age>math_score>french_score
Ray>Morley>18>"68     000">"75                                             000"
Melvin>Scott>24>77>83 NaN                                                   NaN
Amirah>Haley>22>92>67 NaN                                                   NaN
Gerard>Mills>19>"78   000">72                                               NaN
Amy>Grimes>23>91>81   NaN                                                   NaN

In [ ]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>')
exam_df

  first_name last_name  age math_score french_score
0        Ray    Morley   18     68,000       75,000
1     Melvin     Scott   24         77           83
2     Amirah     Haley   22         92           67
3     Gerard     Mills   19     78,000           72
4        Amy    Grimes   23         91           81

In [ ]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>')

exam_df

  first_name last_name  age math_score french_score
0        Ray    Morley   18     68,000       75,000
1     Melvin     Scott   24         77           83
2     Amirah     Haley   22         92           67
3     Gerard     Mills   19     78,000           72
4        Amy    Grimes   23         91           81

In [ ]:
exam_df[['math_score', 'french_score']].dtypes

math_score      object
french_score    object
dtype: object

In [ ]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>',
                      decimal=',')

In [ ]:
exam_df

  first_name last_name  age  math_score  french_score
0        Ray    Morley   18        68.0          75.0
1     Melvin     Scott   24        77.0          83.0
2     Amirah     Haley   22        92.0          67.0
3     Gerard     Mills   19        78.0          72.0
4        Amy    Grimes   23        91.0          81.0

In [ ]:
exam_df[['math_score', 'french_score']].dtypes

math_score      float64
french_score    float64
dtype: object

In [ ]:
pd.read_csv('exam_review.csv',
            sep='>',
            thousands=',')

  first_name last_name  age  math_score  french_score
0        Ray    Morley   18       68000         75000
1     Melvin     Scott   24          77            83
2     Amirah     Haley   22          92            67
3     Gerard     Mills   19       78000            72
4        Amy    Grimes   23          91            81

In [ ]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>',
                      decimal=',')

In [ ]:
exam_df

  first_name last_name  age  math_score  french_score
0        Ray    Morley   18        68.0          75.0
1     Melvin     Scott   24        77.0          83.0
2     Amirah     Haley   22        92.0          67.0
3     Gerard     Mills   19        78.0          72.0
4        Amy    Grimes   23        91.0          81.0

In [ ]:
pd.read_csv('exam_review.csv',
            sep='>',
            skiprows=2)

   Melvin   Scott  24      77  83
0  Amirah   Haley  22      92  67
1  Gerard   Mills  19  78,000  72
2     Amy  Grimes  23      91  81

In [ ]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>',
                      decimal=',',
                      skiprows=[1,3])
exam_df

  first_name last_name  age  math_score  french_score
0     Melvin     Scott   24        77.0            83
1     Gerard     Mills   19        78.0            72
2        Amy    Grimes   23        91.0            81

In [ ]:
pd.read_csv('exam_review.csv',
            sep='>',
            skip_blank_lines=False)

  first_name last_name   age math_score french_score
0        Ray    Morley  18.0     68,000       75,000
1     Melvin     Scott  24.0         77           83
2     Amirah     Haley  22.0         92           67
3        NaN       NaN   NaN        NaN          NaN
4     Gerard     Mills  19.0     78,000           72
5        Amy    Grimes  23.0         91           81

In [ ]:
pd.read_csv('exam_review.csv',
            usecols=['first_name', 'last_name', 'age'],
            sep='>')

  first_name last_name  age
0        Ray    Morley   18
1     Melvin     Scott   24
2     Amirah     Haley   22
3     Gerard     Mills   19
4        Amy    Grimes   23

In [ ]:
pd.read_csv('exam_review.csv',
            usecols=[0, 1, 2],
            sep='>')

  first_name last_name  age
0        Ray    Morley   18
1     Melvin     Scott   24
2     Amirah     Haley   22
3     Gerard     Mills   19
4        Amy    Grimes   23

In [ ]:
exam_test_1 = pd.read_csv('exam_review.csv',
                          sep='>',
                          usecols=['last_name'])

In [ ]:
type(exam_test_1)

pandas.core.frame.DataFrame

In [ ]:
exam_test_2 = pd.read_csv('exam_review.csv',
                          sep='>',
                          usecols=['last_name'],
                          squeeze=True)
type(exam_test_2)

pandas.core.series.Series

In [ ]:
exam_df

  first_name last_name  age  math_score  french_score
0     Melvin     Scott   24        77.0            83
1     Gerard     Mills   19        78.0            72
2        Amy    Grimes   23        91.0            81

In [ ]:
exam_df.to_csv()
exam_df.to_csv('out.csv')
pd.read_csv('out.csv')

   Unnamed: 0 first_name last_name  age  math_score  french_score
0           0     Melvin     Scott   24        77.0            83
1           1     Gerard     Mills   19        78.0            72
2           2        Amy    Grimes   23        91.0            81

In [ ]:
exam_df.to_csv('out.csv',
               index=None)
pd.read_csv('out.csv')

  first_name last_name  age  math_score  french_score
0     Melvin     Scott   24        77.0            83
1     Gerard     Mills   19        78.0            72
2        Amy    Grimes   23        91.0            81

LESSON 2

In [ ]:
import numpy as np
import pandas as pd

column_names = ['color', 'director_name', 'num_critic_for_reviews', 'duration',
                'gross', 'movie_title', 'num_user_for_reviews', 'country',
                'cotent_rating', 'budget', 'title_year', 'imdb_score', 'genre']

movies = pd.read_csv('movies.csv',
                     sep='|',
                     header=None,
                     names=column_names,
                     skiprows=3)
movies.head()

,color,director_name,num_critic_for_reviews,duration,gross,movie_title,num_user_for_reviews,country,cotent_rating,budget,title_year,imdb_score,genre
0,Color,Christopher Nolan,813.0,164.0,448130642.0,The Dark Knight Rises,2701.0,USA,PG-13,"250,000,000.0",2012.0,8.5,Action
1,?,Doug Walker,?,?,?,Star Wars: Episode VII - The Force Awakens ...,?,?,?,?,?,7.1,Documentary
2,Color,Andrew Stanton,462.0,132.0,73058679.0,John Carter,738.0,USA,PG-13,"263,700,000.0",2012.0,6.6,Action
3,Color,Sam Raimi,392.0,156.0,336530303.0,Spider-Man 3,1902.0,USA,PG-13,"258,000,000.0",2007.0,6.2,Action
4,Color,Nathan Greno,324.0,100.0,200807262.0,Tangled,387.0,USA,PG,"260,000,000.0",2010.0,7.8,Adventure

LESSON 3

In [ ]:
import numpy as np
import pandas as pd

column_names = ['color', 'director_name', 'num_critic_for_reviews', 'duration',
                'gross', 'movie_title', 'num_user_for_reviews', 'country',
                'cotent_rating', 'budget', 'title_year', 'imdb_score', 'genre']

movies = pd.read_csv('movies.csv',
                     sep='|',
                     header=None,
                     names=column_names,
                     na_values='?',
                     thousands=',',
                     index_col='movie_title')
movies.head()

,color,director_name,num_critic_for_reviews,duration,gross,num_user_for_reviews,country,cotent_rating,budget,title_year,imdb_score,genre
movie_title,,,,,,,,,,,,
Avatar,Color,James Cameron,723.0,178.0,760505847.0,3054.0,USA,PG-13,237000000.0,2009.0,7.9,Action
Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.0,169.0,309404152.0,1238.0,USA,PG-13,300000000.0,2007.0,7.1,Action
Spectre,Color,Sam Mendes,602.0,148.0,200074175.0,994.0,UK,PG-13,245000000.0,2015.0,6.8,Action
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,448130642.0,2701.0,USA,PG-13,250000000.0,2012.0,8.5,Action
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.1,Documentary

LESSON 4

In [ ]:
import numpy as np
import pandas as pd

col_names = ['Title', 'Air date', 'Production code', 'Season', 'Number in season',
             'Number in series', 'US viewers (million)', 'Views', 'IMDB rating']

select_cols = ['Title','Air date','Production code','IMDB rating']

simpsons = pd.read_csv('simpsons-episodes.tsv',
                 sep='\t',
                 encoding='UTF-8',
                 names=col_names,
                 usecols=select_cols,
                 skiprows=4,
                 index_col='Production code',
                 na_values=['no_val'],
                 parse_dates=['Air date'])
simpsons.head()

,Title,Air date,IMDB rating
Production code,,,
7F01,Two Cars in Every Garage and Three Eyes on Eve...,1990-01-11,8.1
7F08,NaN,1990-11-15,8.0
7F06,Bart the Daredevil,1990-06-12,NaN
NaN,Bart Gets Hit by a Car,1991-10-01,7.8
7F13,Homer vs. Lisa and the 8th Commandment,1991-07-02,8.0

LESSON 5

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('products.xlsx')
df.head()

,product_id,price,merchant_id,brand,name
0,AVphzgbJLJeJML43fA0o,104.99,1001,Sanus,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...
1,AVpgMuGwLJeJML43KY_c,69.00,1002,Boytone,Boytone - 2500W 2.1-Ch. Home Theater System - ...
2,AVpe9FXeLJeJML43zHrq,23.99,1001,DENAQ,DENAQ - AC Adapter for TOSHIBA SATELLITE
3,AVpfVJXu1cnluZ0-iwTT,290.99,1001,DreamWave,DreamWave - Tremor Portable Bluetooth Speaker ...
4,AVphUeKeilAPnD_x3-Be,244.01,1004,Yamaha,NS-SP1800BL 5.1-Channel Home Theater System (B...

In [ ]:
pd.read_excel('products.xlsx').head()
pd.read_excel('products.xlsx',
              header=None).head()

,0,1,2,3,4
0,product_id,price,merchant_id,brand,name
1,AVphzgbJLJeJML43fA0o,104.99,1001,Sanus,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...
2,AVpgMuGwLJeJML43KY_c,69,1002,Boytone,Boytone - 2500W 2.1-Ch. Home Theater System - ...
3,AVpe9FXeLJeJML43zHrq,23.99,1001,DENAQ,DENAQ - AC Adapter for TOSHIBA SATELLITE
4,AVpfVJXu1cnluZ0-iwTT,290.99,1001,DreamWave,DreamWave - Tremor Portable Bluetooth Speaker ...

In [ ]:
df = pd.read_excel('products.xlsx',
                   index_col=[0])
df.head()

,price,merchant_id,brand,name
product_id,,,,
AVphzgbJLJeJML43fA0o,104.99,1001,Sanus,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...
AVpgMuGwLJeJML43KY_c,69.00,1002,Boytone,Boytone - 2500W 2.1-Ch. Home Theater System - ...
AVpe9FXeLJeJML43zHrq,23.99,1001,DENAQ,DENAQ - AC Adapter for TOSHIBA SATELLITE
AVpfVJXu1cnluZ0-iwTT,290.99,1001,DreamWave,DreamWave - Tremor Portable Bluetooth Speaker ...
AVphUeKeilAPnD_x3-Be,244.01,1004,Yamaha,NS-SP1800BL 5.1-Channel Home Theater System (B...

In [ ]:
products = pd.read_excel('products.xlsx',
                         sheet_name='Products',
                         index_col='product_id')
products.head()

,price,merchant_id,brand,name
product_id,,,,
AVphzgbJLJeJML43fA0o,104.99,1001,Sanus,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...
AVpgMuGwLJeJML43KY_c,69.00,1002,Boytone,Boytone - 2500W 2.1-Ch. Home Theater System - ...
AVpe9FXeLJeJML43zHrq,23.99,1001,DENAQ,DENAQ - AC Adapter for TOSHIBA SATELLITE
AVpfVJXu1cnluZ0-iwTT,290.99,1001,DreamWave,DreamWave - Tremor Portable Bluetooth Speaker ...
AVphUeKeilAPnD_x3-Be,244.01,1004,Yamaha,NS-SP1800BL 5.1-Channel Home Theater System (B...

In [ ]:
merchants = pd.read_excel('products.xlsx',
                          sheet_name='Merchants',
                          index_col='merchant_id')
merchants.head()

                     merchant
merchant_id
1001              Bestbuy.com
1002              Walmart.com
1003              Bestbuy.com
1004                 Growkart
1005         bhphotovideo.com

In [ ]:
excel_file = pd.ExcelFile('products.xlsx')
excel_file.sheet_names

['Products', 'Descriptions', 'Merchants']

In [ ]:
products = excel_file.parse('Products')

products.head()

,product_id,price,merchant_id,brand,name
0,AVphzgbJLJeJML43fA0o,104.99,1001,Sanus,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...
1,AVpgMuGwLJeJML43KY_c,69.00,1002,Boytone,Boytone - 2500W 2.1-Ch. Home Theater System - ...
2,AVpe9FXeLJeJML43zHrq,23.99,1001,DENAQ,DENAQ - AC Adapter for TOSHIBA SATELLITE
3,AVpfVJXu1cnluZ0-iwTT,290.99,1001,DreamWave,DreamWave - Tremor Portable Bluetooth Speaker ...
4,AVphUeKeilAPnD_x3-Be,244.01,1004,Yamaha,NS-SP1800BL 5.1-Channel Home Theater System (B...

In [ ]:
products = excel_file.parse(sheet_name='Products',
                            header=0,
                            index_col='product_id')
products.head()

,price,merchant_id,brand,name
product_id,,,,
AVphzgbJLJeJML43fA0o,104.99,1001,Sanus,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...
AVpgMuGwLJeJML43KY_c,69.00,1002,Boytone,Boytone - 2500W 2.1-Ch. Home Theater System - ...
AVpe9FXeLJeJML43zHrq,23.99,1001,DENAQ,DENAQ - AC Adapter for TOSHIBA SATELLITE
AVpfVJXu1cnluZ0-iwTT,290.99,1001,DreamWave,DreamWave - Tremor Portable Bluetooth Speaker ...
AVphUeKeilAPnD_x3-Be,244.01,1004,Yamaha,NS-SP1800BL 5.1-Channel Home Theater System (B...

In [ ]:
products.dtypes

price          float64
merchant_id      int64
brand           object
name            object
dtype: object

In [ ]:
merchants = excel_file.parse('Merchants',
                             index_col='merchant_id')
merchants.head()

merchants.dtypes

merchant    object
dtype: object

In [ ]:
products.head()

,price,merchant_id,brand,name
product_id,,,,
AVphzgbJLJeJML43fA0o,104.99,1001,Sanus,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...
AVpgMuGwLJeJML43KY_c,69.00,1002,Boytone,Boytone - 2500W 2.1-Ch. Home Theater System - ...
AVpe9FXeLJeJML43zHrq,23.99,1001,DENAQ,DENAQ - AC Adapter for TOSHIBA SATELLITE
AVpfVJXu1cnluZ0-iwTT,290.99,1001,DreamWave,DreamWave - Tremor Portable Bluetooth Speaker ...
AVphUeKeilAPnD_x3-Be,244.01,1004,Yamaha,NS-SP1800BL 5.1-Channel Home Theater System (B...

In [ ]:
products.to_excel('out.xlsx')

pd.read_excel('out.xlsx').head()

,product_id,price,merchant_id,brand,name
0,AVphzgbJLJeJML43fA0o,104.99,1001,Sanus,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...
1,AVpgMuGwLJeJML43KY_c,69.00,1002,Boytone,Boytone - 2500W 2.1-Ch. Home Theater System - ...
2,AVpe9FXeLJeJML43zHrq,23.99,1001,DENAQ,DENAQ - AC Adapter for TOSHIBA SATELLITE
3,AVpfVJXu1cnluZ0-iwTT,290.99,1001,DreamWave,DreamWave - Tremor Portable Bluetooth Speaker ...
4,AVphUeKeilAPnD_x3-Be,244.01,1004,Yamaha,NS-SP1800BL 5.1-Channel Home Theater System (B...

In [ ]:
products.to_excel('out.xlsx',
                  sheet_name='Products')
products.to_excel('out.xlsx',
                  index=None)
pd.read_excel('out.xlsx').head()

,price,merchant_id,brand,name
0,104.99,1001,Sanus,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...
1,69.00,1002,Boytone,Boytone - 2500W 2.1-Ch. Home Theater System - ...
2,23.99,1001,DENAQ,DENAQ - AC Adapter for TOSHIBA SATELLITE
3,290.99,1001,DreamWave,DreamWave - Tremor Portable Bluetooth Speaker ...
4,244.01,1004,Yamaha,NS-SP1800BL 5.1-Channel Home Theater System (B...

In [ ]:
writer = pd.ExcelWriter('out.xlsx')

writer

In [ ]:
with writer:
    products.to_excel(writer, sheet_name='Products')

In [ ]:
pd.read_excel('out.xlsx', sheet_name='Products').head()

,product_id,price,merchant_id,brand,name
0,AVphzgbJLJeJML43fA0o,104.99,1001,Sanus,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...
1,AVpgMuGwLJeJML43KY_c,69.00,1002,Boytone,Boytone - 2500W 2.1-Ch. Home Theater System - ...
2,AVpe9FXeLJeJML43zHrq,23.99,1001,DENAQ,DENAQ - AC Adapter for TOSHIBA SATELLITE
3,AVpfVJXu1cnluZ0-iwTT,290.99,1001,DreamWave,DreamWave - Tremor Portable Bluetooth Speaker ...
4,AVphUeKeilAPnD_x3-Be,244.01,1004,Yamaha,NS-SP1800BL 5.1-Channel Home Theater System (B...

In [ ]:
with pd.ExcelWriter('out.xlsx') as writer:
    products.to_excel(writer, sheet_name='Products')
    merchants.to_excel(writer, sheet_name='Merchants')

LESSON 6

In [ ]:
import numpy as np
import pandas as pd

data_url = 'https://github.com/ine-rmotr-projects/project-files/files/4086772/playstore.xlsx'

playstore_df = pd.read_excel(data_url,
                   parse_dates=['Last_Updated'],
                   usecols=['App', 'Rating', 'Installs', 'Rating', 'Genres', 'Last_Updated'])

playstore_df = playstore_df.sort_values('Rating', ascending=False).head(25)
playstore_df.head()

,App,Rating,Installs,Genres,Last_Updated
99,"ipsy: Makeup, Beauty, and Tips",4.9,"1,000,000+",Beauty,2017-11-09
61,CDL Practice Test 2018 Edition,4.9,"100,000+",Auto & Vehicles,2018-07-03
79,Tickets + PDA 2018 Exam,4.9,"1,000,000+",Auto & Vehicles,2018-07-15
64,DMV Permit Practice Test 2018 Edition,4.9,"100,000+",Auto & Vehicles,2018-07-03
177,eBoox new: Reader for fb2 epub zip books,4.9,"50,000+",Books & Reference,2018-07-17

LESSON 7

In [ ]:
import numpy as np
import pandas as pd

data_url = 'https://github.com/ine-rmotr-projects/project-files/files/4086772/playstore.xlsx'

file = pd.ExcelFile(data_url)

playstore_df = file.parse(index_col=0)

content_id_df = file.parse('Content_ID', 
                          index_col='Content_ID')
content_id_df.head()

           Content_Rating
Content_ID
101.0            Everyone
101.0            Everyone
101.0            Everyone
102.0                Teen
101.0            Everyone

LESSON 8

In [ ]:
!head -n20 games.json

[
    {
        "title": "Call of Duty®: WWII + Destiny 2 - Lote",
        "price": "129,99 €",
        "content_rating_img": "https://cdn-a.sonyentertainmentnetwork.com/grc/images/ratings/hd/pegi/18.png",
        "release_date": "Dic 21 2018",
        "provider": "Activision Blizzard Int'l BV",
        "genre": "Shooter",
        "image": "https://store.playstation.com/store/api/chihiro/00_09_000/container/ES/es/999/EP0002-CUSA08633_00-CODWWIIANDD2BASE/1516962740000/image?w=240&h=240&bg_color=000000&opacity=100&_version=00_09_000"
    },
    {
        "title": "God of War® Digital Deluxe Edition",
        "price": "69,99 €",
        "content_rating_img": "https://cdn-a.sonyentertainmentnetwork.com/grc/images/ratings/hd/pegi/18.png",
        "release_date": "Abr 20 2018",
        "provider": "Sony Interactive Entertainment Europe",
        "genre": "Acción",
        "image": "https://store.playstation.com/store/api/chihiro/00_09_000/container/ES/es/999/EP9000-CUSA07411_00-GOW2018PREORDPSN/1517129711000/image?w=240&h=240&bg_color=000000&opacity=100&_version=00_09_000"
    },
    {

In [ ]:
games = pd.read_json('games.json')

games.head()

,title,price,content_rating_img,release_date,provider,genre,image
0,Call of Duty®: WWII + Destiny 2 - Lote,"129,99 €",https://cdn-a.sonyentertainmentnetwork.com/grc...,Dic 21 2018,Activision Blizzard Int'l BV,Shooter,https://store.playstation.com/store/api/chihir...
1,God of War® Digital Deluxe Edition,"69,99 €",https://cdn-a.sonyentertainmentnetwork.com/grc...,Abr 20 2018,Sony Interactive Entertainment Europe,Acción,https://store.playstation.com/store/api/chihir...
2,Far Cry 5,"69,99 €",https://cdn-a.sonyentertainmentnetwork.com/grc...,Mar 27 2018,UBISOFT ENTERTAINMENT SA,Aventura,https://store.playstation.com/store/api/chihir...
3,Far Cry 5 Edición Deluxe,"79,99 €",https://cdn-a.sonyentertainmentnetwork.com/grc...,Mar 27 2018,UBISOFT ENTERTAINMENT SA,Aventura,https://store.playstation.com/store/api/chihir...
4,Far Cry 5 Edición Oro,"89,99 €",https://cdn-a.sonyentertainmentnetwork.com/grc...,Mar 27 2018,UBISOFT ENTERTAINMENT SA,Aventura,https://store.playstation.com/store/api/chihir...

In [ ]:
!head -n20 users.json

{
  "info": [
    {
      "id": 1,
      "name": "Leanne Graham",
      "username": "Bret",
      "email": "Sincere@april.biz",
      "address": [{
        "street": "Kulas Light",
        "suite": "Apt. 556",
        "city": "Gwenborough",
        "zipcode": "92998-3874",
        "geo": {
          "lat": "-37.3159",
          "lng": "81.1496"
        }
      }],
      "phone": "1-770-736-8031 x56442",
      "website": "hildegard.org",
      "company": {

In [ ]:
df = pd.read_json('users.json')

df.head()

                                                info
0  {'id': 1, 'name': 'Leanne Graham', 'username':...
1  {'id': 2, 'name': 'Ervin Howell', 'username': ...
2  {'id': 3, 'name': 'Clementine Bauch', 'usernam...
3  {'id': 4, 'name': 'Patricia Lebsack', 'usernam...
4  {'id': 5, 'name': 'Chelsey Dietrich', 'usernam...

In [ ]:
import json

with open('users.json') as file:
    json_dict = json.load(file)
json_dict

{'info': [{'id': 1,
   'name': 'Leanne Graham',
   'username': 'Bret',
   'email': 'Sincere@april.biz',
   'address': [{'street': 'Kulas Light',
     'suite': 'Apt. 556',
     'city': 'Gwenborough',
     'zipcode': '92998-3874',
     'geo': {'lat': '-37.3159', 'lng': '81.1496'}}],
   'phone': '1-770-736-8031 x56442',
   'website': 'hildegard.org',
   'company': {'name': 'Romaguera-Crona',
    'catchPhrase': 'Multi-layered client-server neural-net',
    'bs': 'harness real-time e-markets'}},
  {'id': 2,
   'name': 'Ervin Howell',
   'username': 'Antonette',
   'email': 'Shanna@melissa.tv',
   'address': [{'street': 'Victor Plains',
     'suite': 'Suite 879',
     'city': 'Wisokyburgh',
     'zipcode': '90566-7771',
     'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}],
   'phone': '010-692-6593 x09125',
   'website': 'anastasia.net',
   'company': {'name': 'Deckow-Crist',
    'catchPhrase': 'Proactive didactic contingency',
    'bs': 'synergize scalable supply-chains'}},
  {'id': 3,
   'name': 'Clementine Bauch',
   'username': 'Samantha',
   'email': 'Nathan@yesenia.net',
   'address': [{'street': 'Douglas Extension',
     'suite': 'Suite 847',
     'city': 'McKenziehaven',
     'zipcode': '59590-4157',
     'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}],
   'phone': '1-463-123-4447',
   'website': 'ramiro.info',
   'company': {'name': 'Romaguera-Jacobson',
    'catchPhrase': 'Face to face bifurcated interface',
    'bs': 'e-enable strategic applications'}},
  {'id': 4,
   'name': 'Patricia Lebsack',
   'username': 'Karianne',
   'email': 'Julianne.OConner@kory.org',
   'address': [{'street': 'Hoeger Mall',
     'suite': 'Apt. 692',
     'city': 'South Elvis',
     'zipcode': '53919-4257',
     'geo': {'lat': '29.4572', 'lng': '-164.2990'}}],
   'phone': '493-170-9623 x156',
   'website': 'kale.biz',
   'company': {'name': 'Robel-Corkery',
    'catchPhrase': 'Multi-tiered zero tolerance productivity',
    'bs': 'transition cutting-edge web services'}},
  {'id': 5,
   'name': 'Chelsey Dietrich',
   'username': 'Kamren',
   'email': 'Lucio_Hettinger@annie.ca',
   'address': [{'street': 'Skiles Walks',
     'suite': 'Suite 351',
     'city': 'Roscoeview',
     'zipcode': '33263',
     'geo': {'lat': '-31.8129', 'lng': '62.5342'}}],
   'phone': '(254)954-1289',
   'website': 'demarco.info',
   'company': {'name': 'Keebler LLC',
    'catchPhrase': 'User-centric fault-tolerant solution',
    'bs': 'revolutionize end-to-end systems'}},
  {'id': 6,
   'name': 'Mrs. Dennis Schulist',
   'username': 'Leopoldo_Corkery',
   'email': 'Karley_Dach@jasper.info',
   'address': [{'street': 'Norberto Crossing',
     'suite': 'Apt. 950',
     'city': 'South Christy',
     'zipcode': '23505-1337',
     'geo': {'lat': '-71.4197', 'lng': '71.7478'}}],
   'phone': '1-477-935-8478 x6430',
   'website': 'ola.org',
   'company': {'name': 'Considine-Lockman',
    'catchPhrase': 'Synchronised bottom-line interface',
    'bs': 'e-enable innovative applications'}},
  {'id': 7,
   'name': 'Kurtis Weissnat',
   'username': 'Elwyn.Skiles',
   'email': 'Telly.Hoeger@billy.biz',
   'address': [{'street': 'Rex Trail',
     'suite': 'Suite 280',
     'city': 'Howemouth',
     'zipcode': '58804-1099',
     'geo': {'lat': '24.8918', 'lng': '21.8984'}}],
   'phone': '210.067.6132',
   'website': 'elvis.io',
   'company': {'name': 'Johns Group',
    'catchPhrase': 'Configurable multimedia task-force',
    'bs': 'generate enterprise e-tailers'}},
  {'id': 8,
   'name': 'Nicholas Runolfsdottir V',
   'username': 'Maxime_Nienow',
   'email': 'Sherwood@rosamond.me',
   'address': [{'street': 'Ellsworth Summit',
     'suite': 'Suite 729',
     'city': 'Aliyaview',
     'zipcode': '45169',
     'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}],
   'phone': '586.493.6943 x140',
   'website': 'jacynthe.com',
   'company': {'name': 'Abernathy Group',
    'catchPhrase': 'Implemented secondary concept',
    'bs': 'e-enable extensible e-tailers'}},
  {'id': 9,
   'name': 'Glenna Reichert',
   'username': 'Delphine',
   'email': 'Chaim_McDermott@dana.io',
   'address': [{'street': 'Dayna Park',
     'suite': 'Suite 449',
     'city': 'Bartholomebury',
     'zipcode': '76495-3109',
     'geo': {'lat': '24.6463', 'lng': '-168.8889'}}],
   'phone': '(775)976-6794 x41206',
   'website': 'conrad.com',
   'company': {'name': 'Yost and Sons',
    'catchPhrase': 'Switchable contextually-based project',
    'bs': 'aggregate real-time technologies'}},
  {'id': 10,
   'name': 'Clementina DuBuque',
   'username': 'Moriah.Stanton',
   'email': 'Rey.Padberg@karina.biz',
   'address': [{'street': 'Kattie Turnpike',
     'suite': 'Suite 198',
     'city': 'Lebsackbury',
     'zipcode': '31428-2261',
     'geo': {'lat': '-38.2386', 'lng': '57.2232'}}],
   'phone': '024-648-3804',
   'website': 'ambrose.net',
   'company': {'name': 'Hoeger LLC',
    'catchPhrase': 'Centralized empowering task-force',
    'bs': 'target end-to-end models'}}]}

In [ ]:
json_dict.keys()

dict_keys(['info'])

In [ ]:
json_dict.values()

dict_values([[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': [{'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}], 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}, {'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': [{'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}], 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}, {'id': 3, 'name': 'Clementine Bauch', 'username': 'Samantha', 'email': 'Nathan@yesenia.net', 'address': [{'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}], 'phone': '1-463-123-4447', 'website': 'ramiro.info', 'company': {'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'}}, {'id': 4, 'name': 'Patricia Lebsack', 'username': 'Karianne', 'email': 'Julianne.OConner@kory.org', 'address': [{'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}}], 'phone': '493-170-9623 x156', 'website': 'kale.biz', 'company': {'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'}}, {'id': 5, 'name': 'Chelsey Dietrich', 'username': 'Kamren', 'email': 'Lucio_Hettinger@annie.ca', 'address': [{'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}}], 'phone': '(254)954-1289', 'website': 'demarco.info', 'company': {'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'}}, {'id': 6, 'name': 'Mrs. Dennis Schulist', 'username': 'Leopoldo_Corkery', 'email': 'Karley_Dach@jasper.info', 'address': [{'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}}], 'phone': '1-477-935-8478 x6430', 'website': 'ola.org', 'company': {'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'}}, {'id': 7, 'name': 'Kurtis Weissnat', 'username': 'Elwyn.Skiles', 'email': 'Telly.Hoeger@billy.biz', 'address': [{'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}}], 'phone': '210.067.6132', 'website': 'elvis.io', 'company': {'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'}}, {'id': 8, 'name': 'Nicholas Runolfsdottir V', 'username': 'Maxime_Nienow', 'email': 'Sherwood@rosamond.me', 'address': [{'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}], 'phone': '586.493.6943 x140', 'website': 'jacynthe.com', 'company': {'name': 'Abernathy Group', 'catchPhrase': 'Implemented secondary concept', 'bs': 'e-enable extensible e-tailers'}}, {'id': 9, 'name': 'Glenna Reichert', 'username': 'Delphine', 'email': 'Chaim_McDermott@dana.io', 'address': [{'street': 'Dayna Park', 'suite': 'Suite 449', 'city': 'Bartholomebury', 'zipcode': '76495-3109', 'geo': {'lat': '24.6463', 'lng': '-168.8889'}}], 'phone': '(775)976-6794 x41206', 'website': 'conrad.com', 'company': {'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'}}, {'id': 10, 'name': 'Clementina DuBuque', 'username': 'Moriah.Stanton', 'email': 'Rey.Padberg@karina.biz', 'address': [{'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}}], 'phone': '024-648-3804', 'website': 'ambrose.net', 'company': {'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'}}]])

In [ ]:
for user in json_dict['info']:
    print(user)

{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': [{'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}], 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}
{'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': [{'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}], 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}
{'id': 3, 'name': 'Clementine Bauch', 'username': 'Samantha', 'email': 'Nathan@yesenia.net', 'address': [{'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}], 'phone': '1-463-123-4447', 'website': 'ramiro.info', 'company': {'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'}}
{'id': 4, 'name': 'Patricia Lebsack', 'username': 'Karianne', 'email': 'Julianne.OConner@kory.org', 'address': [{'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}}], 'phone': '493-170-9623 x156', 'website': 'kale.biz', 'company': {'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'}}
{'id': 5, 'name': 'Chelsey Dietrich', 'username': 'Kamren', 'email': 'Lucio_Hettinger@annie.ca', 'address': [{'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}}], 'phone': '(254)954-1289', 'website': 'demarco.info', 'company': {'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'}}
{'id': 6, 'name': 'Mrs. Dennis Schulist', 'username': 'Leopoldo_Corkery', 'email': 'Karley_Dach@jasper.info', 'address': [{'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}}], 'phone': '1-477-935-8478 x6430', 'website': 'ola.org', 'company': {'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'}}
{'id': 7, 'name': 'Kurtis Weissnat', 'username': 'Elwyn.Skiles', 'email': 'Telly.Hoeger@billy.biz', 'address': [{'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}}], 'phone': '210.067.6132', 'website': 'elvis.io', 'company': {'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'}}
{'id': 8, 'name': 'Nicholas Runolfsdottir V', 'username': 'Maxime_Nienow', 'email': 'Sherwood@rosamond.me', 'address': [{'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}], 'phone': '586.493.6943 x140', 'website': 'jacynthe.com', 'company': {'name': 'Abernathy Group', 'catchPhrase': 'Implemented secondary concept', 'bs': 'e-enable extensible e-tailers'}}
{'id': 9, 'name': 'Glenna Reichert', 'username': 'Delphine', 'email': 'Chaim_McDermott@dana.io', 'address': [{'street': 'Dayna Park', 'suite': 'Suite 449', 'city': 'Bartholomebury', 'zipcode': '76495-3109', 'geo': {'lat': '24.6463', 'lng': '-168.8889'}}], 'phone': '(775)976-6794 x41206', 'website': 'conrad.com', 'company': {'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'}}
{'id': 10, 'name': 'Clementina DuBuque', 'username': 'Moriah.Stanton', 'email': 'Rey.Padberg@karina.biz', 'address': [{'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}}], 'phone': '024-648-3804', 'website': 'ambrose.net', 'company': {'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'}}

In [ ]:
pd.DataFrame.from_dict({'Fruits': ['Apple', 'Banana']})

   Fruits
0   Apple
1  Banana

In [ ]:
pd.DataFrame.from_dict({'Fruits': ['Apple', 'Banana']}, orient='index')

            0       1
Fruits  Apple  Banana

In [ ]:
df = pd.DataFrame.from_dict(json_dict)

df.head()

                                                info
0  {'id': 1, 'name': 'Leanne Graham', 'username':...
1  {'id': 2, 'name': 'Ervin Howell', 'username': ...
2  {'id': 3, 'name': 'Clementine Bauch', 'usernam...
3  {'id': 4, 'name': 'Patricia Lebsack', 'usernam...
4  {'id': 5, 'name': 'Chelsey Dietrich', 'usernam...

In [ ]:
df = pd.DataFrame.from_dict(json_dict['info'])

df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"[{'street': 'Kulas Light', 'suite': 'Apt. 556'...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"[{'street': 'Victor Plains', 'suite': 'Suite 8...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"[{'street': 'Douglas Extension', 'suite': 'Sui...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"[{'street': 'Hoeger Mall', 'suite': 'Apt. 692'...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"[{'street': 'Skiles Walks', 'suite': 'Suite 35...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [ ]:
from pandas.io.json import json_normalize

users = json_normalize(json_dict)

users

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  This is separate from the ipykernel package so we can avoid doing imports until

                                                info
0  [{'id': 1, 'name': 'Leanne Graham', 'username'...

In [ ]:
users = json_normalize(json_dict['info'])

users.head(3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  """Entry point for launching an IPython kernel.

,id,name,username,email,address,phone,website,company.name,company.catchPhrase,company.bs
0,1,Leanne Graham,Bret,Sincere@april.biz,"[{'street': 'Kulas Light', 'suite': 'Apt. 556'...",1-770-736-8031 x56442,hildegard.org,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"[{'street': 'Victor Plains', 'suite': 'Suite 8...",010-692-6593 x09125,anastasia.net,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"[{'street': 'Douglas Extension', 'suite': 'Sui...",1-463-123-4447,ramiro.info,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications

In [ ]:
users = json_normalize(json_dict['info'],
                       sep='_')
users.head(3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

,id,name,username,email,address,phone,website,company_name,company_catchPhrase,company_bs
0,1,Leanne Graham,Bret,Sincere@april.biz,"[{'street': 'Kulas Light', 'suite': 'Apt. 556'...",1-770-736-8031 x56442,hildegard.org,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"[{'street': 'Victor Plains', 'suite': 'Suite 8...",010-692-6593 x09125,anastasia.net,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"[{'street': 'Douglas Extension', 'suite': 'Sui...",1-463-123-4447,ramiro.info,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications

In [ ]:
address = json_normalize(json_dict['info'],
                         sep='_',
                         record_path='address')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
address.head()

,street,suite,city,zipcode,geo_lat,geo_lng
0,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496
1,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618
2,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653
3,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990
4,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342

In [ ]:
address = json_normalize(json_dict,
                         sep='_',
                         record_path=['info', 'address'])
address.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  This is separate from the ipykernel package so we can avoid doing imports until

,street,suite,city,zipcode,geo_lat,geo_lng
0,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496
1,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618
2,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653
3,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990
4,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342

In [ ]:
address = json_normalize(json_dict['info'],
                         sep='_',
                         record_path='address',
                         meta=['id'])
address.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  after removing the cwd from sys.path.

,street,suite,city,zipcode,geo_lat,geo_lng,id
0,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,1
1,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,2
2,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,3
3,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,4
4,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,5

In [ ]:
users.to_json()

'{"id":{"0":1,"1":2,"2":3,"3":4,"4":5,"5":6,"6":7,"7":8,"8":9,"9":10},"name":{"0":"Leanne Graham","1":"Ervin Howell","2":"Clementine Bauch","3":"Patricia Lebsack","4":"Chelsey Dietrich","5":"Mrs. Dennis Schulist","6":"Kurtis Weissnat","7":"Nicholas Runolfsdottir V","8":"Glenna Reichert","9":"Clementina DuBuque"},"username":{"0":"Bret","1":"Antonette","2":"Samantha","3":"Karianne","4":"Kamren","5":"Leopoldo_Corkery","6":"Elwyn.Skiles","7":"Maxime_Nienow","8":"Delphine","9":"Moriah.Stanton"},"email":{"0":"Sincere@april.biz","1":"Shanna@melissa.tv","2":"Nathan@yesenia.net","3":"Julianne.OConner@kory.org","4":"Lucio_Hettinger@annie.ca","5":"Karley_Dach@jasper.info","6":"Telly.Hoeger@billy.biz","7":"Sherwood@rosamond.me","8":"Chaim_McDermott@dana.io","9":"Rey.Padberg@karina.biz"},"address":{"0":[{"street":"Kulas Light","suite":"Apt. 556","city":"Gwenborough","zipcode":"92998-3874","geo":{"lat":"-37.3159","lng":"81.1496"}}],"1":[{"street":"Victor Plains","suite":"Suite 879","city":"Wisokyburgh","zipcode":"90566-7771","geo":{"lat":"-43.9509","lng":"-34.4618"}}],"2":[{"street":"Douglas Extension","suite":"Suite 847","city":"McKenziehaven","zipcode":"59590-4157","geo":{"lat":"-68.6102","lng":"-47.0653"}}],"3":[{"street":"Hoeger Mall","suite":"Apt. 692","city":"South Elvis","zipcode":"53919-4257","geo":{"lat":"29.4572","lng":"-164.2990"}}],"4":[{"street":"Skiles Walks","suite":"Suite 351","city":"Roscoeview","zipcode":"33263","geo":{"lat":"-31.8129","lng":"62.5342"}}],"5":[{"street":"Norberto Crossing","suite":"Apt. 950","city":"South Christy","zipcode":"23505-1337","geo":{"lat":"-71.4197","lng":"71.7478"}}],"6":[{"street":"Rex Trail","suite":"Suite 280","city":"Howemouth","zipcode":"58804-1099","geo":{"lat":"24.8918","lng":"21.8984"}}],"7":[{"street":"Ellsworth Summit","suite":"Suite 729","city":"Aliyaview","zipcode":"45169","geo":{"lat":"-14.3990","lng":"-120.7677"}}],"8":[{"street":"Dayna Park","suite":"Suite 449","city":"Bartholomebury","zipcode":"76495-3109","geo":{"lat":"24.6463","lng":"-168.8889"}}],"9":[{"street":"Kattie Turnpike","suite":"Suite 198","city":"Lebsackbury","zipcode":"31428-2261","geo":{"lat":"-38.2386","lng":"57.2232"}}]},"phone":{"0":"1-770-736-8031 x56442","1":"010-692-6593 x09125","2":"1-463-123-4447","3":"493-170-9623 x156","4":"(254)954-1289","5":"1-477-935-8478 x6430","6":"210.067.6132","7":"586.493.6943 x140","8":"(775)976-6794 x41206","9":"024-648-3804"},"website":{"0":"hildegard.org","1":"anastasia.net","2":"ramiro.info","3":"kale.biz","4":"demarco.info","5":"ola.org","6":"elvis.io","7":"jacynthe.com","8":"conrad.com","9":"ambrose.net"},"company_name":{"0":"Romaguera-Crona","1":"Deckow-Crist","2":"Romaguera-Jacobson","3":"Robel-Corkery","4":"Keebler LLC","5":"Considine-Lockman","6":"Johns Group","7":"Abernathy Group","8":"Yost and Sons","9":"Hoeger LLC"},"company_catchPhrase":{"0":"Multi-layered client-server neural-net","1":"Proactive didactic contingency","2":"Face to face bifurcated interface","3":"Multi-tiered zero tolerance productivity","4":"User-centric fault-tolerant solution","5":"Synchronised bottom-line interface","6":"Configurable multimedia task-force","7":"Implemented secondary concept","8":"Switchable contextually-based project","9":"Centralized empowering task-force"},"company_bs":{"0":"harness real-time e-markets","1":"synergize scalable supply-chains","2":"e-enable strategic applications","3":"transition cutting-edge web services","4":"revolutionize end-to-end systems","5":"e-enable innovative applications","6":"generate enterprise e-tailers","7":"e-enable extensible e-tailers","8":"aggregate real-time technologies","9":"target end-to-end models"}}'

In [ ]:
users.to_json('out.json')

pd.read_json('out.json').head()

,id,name,username,email,address,phone,website,company_name,company_catchPhrase,company_bs
0,1,Leanne Graham,Bret,Sincere@april.biz,"[{'street': 'Kulas Light', 'suite': 'Apt. 556'...",1-770-736-8031 x56442,hildegard.org,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"[{'street': 'Victor Plains', 'suite': 'Suite 8...",010-692-6593 x09125,anastasia.net,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"[{'street': 'Douglas Extension', 'suite': 'Sui...",1-463-123-4447,ramiro.info,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"[{'street': 'Hoeger Mall', 'suite': 'Apt. 692'...",493-170-9623 x156,kale.biz,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"[{'street': 'Skiles Walks', 'suite': 'Suite 35...",(254)954-1289,demarco.info,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems

LESSON 9

In [ ]:
import numpy as np
import pandas as pd

artists = pd.read_json('artists.json')

artists.drop(['bio'], axis='columns', inplace=True)

artists.set_index('name', inplace=True)

artists.to_csv('artists.csv')

LESSON 10

In [ ]:
import numpy as np
import pandas as pd
import json
from pandas.io.json import json_normalize

with open('artists.json') as file:
    json_dict = json.load(file)

artists = json_normalize(json_dict)

biography = json_normalize(json_dict,
                           record_path='bio',
                           meta=['name'])
biography.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  del sys.path[0]

,full name,pronunciation,life span,info,wikipedia,paintings,name
0,Amedeo Clemente Modigliani,[ameˈdɛːo modiʎˈʎaːni],12 July 1884 – 24 January 1920,was an Italian Jewish painter and sculptor who...,http://en.wikipedia.org/wiki/Amedeo_Modigliani,193,Amedeo Modigliani
1,Wassily Wassilyevich Kandinsky,"Васи́лий Васи́льевич Канди́нский, tr. Vasíliy ...",16 December [O.S. 4 December] 1866 – 13 Decemb...,was a Russian painter and art theorist.,http://en.wikipedia.org/wiki/Wassily_Kandinsky,88,Vasiliy Kandinskiy
2,Diego María de la Concepción Juan Nepomuceno E...,[ˈdjeɣo riˈβeɾa],"December 8, 1886 – November 24, 1957",was a prominent Mexican painter. His large fre...,http://en.wikipedia.org/wiki/Diego_Rivera,70,Diego Rivera
3,Oscar-Claude Monet,[klod mɔnɛ],14 November 1840 – 5 December 1926,"was a French painter, a founder of French Impr...",http://en.wikipedia.org/wiki/Claude_Monet,73,Claude Monet
4,René François Ghislain Magritte,[ʁəne fʁɑ̃swa ɡilɛ̃ maɡʁit],21 November 1898 – 15 August 1967,Was a Belgian Surrealist artist. He became wel...,http://en.wikipedia.org/wiki/René_Magritte,194,Rene Magritte

LESSON 11

In [ ]:
!pip install sqlalchemy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (1.4.41)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy) (4.12.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy) (1.1.3)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy) (3.8.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy) (4.1.1)

In [ ]:
import sqlite3

In [ ]:
conn = sqlite3.connect('chinook.db')

In [ ]:
cur = conn.cursor()

In [ ]:
cur.execute('SELECT * FROM employees LIMIT 5;')

In [ ]:
results = cur.fetchall()
results

[(1,
  'Adams',
  'Andrew',
  'General Manager',
  None,
  '1962-02-18 00:00:00',
  '2002-08-14 00:00:00',
  '11120 Jasper Ave NW',
  'Edmonton',
  'AB',
  'Canada',
  'T5K 2N1',
  '+1 (780) 428-9482',
  '+1 (780) 428-3457',
  'andrew@chinookcorp.com'),
 (2,
  'Edwards',
  'Nancy',
  'Sales Manager',
  1,
  '1958-12-08 00:00:00',
  '2002-05-01 00:00:00',
  '825 8 Ave SW',
  'Calgary',
  'AB',
  'Canada',
  'T2P 2T3',
  '+1 (403) 262-3443',
  '+1 (403) 262-3322',
  'nancy@chinookcorp.com'),
 (3,
  'Peacock',
  'Jane',
  'Sales Support Agent',
  2,
  '1973-08-29 00:00:00',
  '2002-04-01 00:00:00',
  '1111 6 Ave SW',
  'Calgary',
  'AB',
  'Canada',
  'T2P 5M5',
  '+1 (403) 262-3443',
  '+1 (403) 262-6712',
  'jane@chinookcorp.com'),
 (4,
  'Park',
  'Margaret',
  'Sales Support Agent',
  2,
  '1947-09-19 00:00:00',
  '2003-05-03 00:00:00',
  '683 10 Street SW',
  'Calgary',
  'AB',
  'Canada',
  'T2P 5G3',
  '+1 (403) 263-4423',
  '+1 (403) 263-4289',
  'margaret@chinookcorp.com'),
 (5,
  'Johnson',
  'Steve',
  'Sales Support Agent',
  2,
  '1965-03-03 00:00:00',
  '2003-10-17 00:00:00',
  '7727B 41 Ave',
  'Calgary',
  'AB',
  'Canada',
  'T3B 1Y7',
  '1 (780) 836-9987',
  '1 (780) 836-9543',
  'steve@chinookcorp.com')]

In [ ]:
df = pd.DataFrame(results)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [ ]:
cur.close()
conn.close()

In [ ]:
conn = sqlite3.connect('chinook.db')
df = pd.read_sql('SELECT * FROM employees;', conn)
df.head()

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [ ]:
df = pd.read_sql('SELECT * FROM employees;', conn,
                 index_col='EmployeeId',
                 parse_dates=['BirthDate', 'HireDate'])
df.head()

,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
EmployeeId,,,,,,,,,,,,,,
1,Adams,Andrew,General Manager,NaN,1962-02-18,2002-08-14,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
2,Edwards,Nancy,Sales Manager,1.0,1958-12-08,2002-05-01,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29,2002-04-01,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
4,Park,Margaret,Sales Support Agent,2.0,1947-09-19,2003-05-03,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03,2003-10-17,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [ ]:


df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8 entries, 1 to 8
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LastName    8 non-null      object
 1   FirstName   8 non-null      object
 2   Title       8 non-null      object
 3   ReportsTo   7 non-null      float64
 4   BirthDate   8 non-null      datetime64[ns]
 5   HireDate    8 non-null      datetime64[ns]
 6   Address     8 non-null      object
 7   City        8 non-null      object
 8   State       8 non-null      object
 9   Country     8 non-null      object
 10  PostalCode  8 non-null      object
 11  Phone       8 non-null      object
 12  Fax         8 non-null      object
 13  Email       8 non-null      object
dtypes: datetime64[ns](2), float64(1), object(11)
memory usage: 960.0+ bytes

In [ ]:
df['ReportsTo'].isna().sum()
df['ReportsTo'].mean()

2.857142857142857

In [ ]:
df['ReportsTo'] > 1.75

EmployeeId
1    False
2    False
3     True
4     True
5     True
6    False
7     True
8     True
Name: ReportsTo, dtype: bool

In [ ]:
df['City'] = df['City'].astype('category')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8 entries, 1 to 8
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LastName    8 non-null      object
 1   FirstName   8 non-null      object
 2   Title       8 non-null      object
 3   ReportsTo   7 non-null      float64
 4   BirthDate   8 non-null      datetime64[ns]
 5   HireDate    8 non-null      datetime64[ns]
 6   Address     8 non-null      object
 7   City        8 non-null      category
 8   State       8 non-null      object
 9   Country     8 non-null      object
 10  PostalCode  8 non-null      object
 11  Phone       8 non-null      object
 12  Fax         8 non-null      object
 13  Email       8 non-null      object
dtypes: category(1), datetime64[ns](2), float64(1), object(10)
memory usage: 1.0+ KB

In [ ]:
conn = sqlite3.connect('chinook.db')
df = pd.read_sql_query('SELECT * FROM employees LIMIT 5;', conn)
df.head()

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [ ]:
df = pd.read_sql_query('SELECT * FROM employees;', conn,
                       index_col='EmployeeId',
                       parse_dates=['BirthDate', 'HireDate'])
df.head()

,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
EmployeeId,,,,,,,,,,,,,,
1,Adams,Andrew,General Manager,NaN,1962-02-18,2002-08-14,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
2,Edwards,Nancy,Sales Manager,1.0,1958-12-08,2002-05-01,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29,2002-04-01,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
4,Park,Margaret,Sales Support Agent,2.0,1947-09-19,2003-05-03,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03,2003-10-17,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [ ]:
from sqlalchemy import create_engine


engine = create_engine('sqlite:///chinook.db')

connection = engine.connect()

df = pd.read_sql_table('employees', con=connection)

df.head()

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18,2002-08-14,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08,2002-05-01,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29,2002-04-01,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19,2003-05-03,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03,2003-10-17,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [ ]:
df = pd.read_sql_table('employees', con=connection,
                       index_col='EmployeeId',
                       parse_dates=['BirthDate', 'HireDate'])
df.head()

,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
EmployeeId,,,,,,,,,,,,,,
1,Adams,Andrew,General Manager,NaN,1962-02-18,2002-08-14,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
2,Edwards,Nancy,Sales Manager,1.0,1958-12-08,2002-05-01,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29,2002-04-01,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
4,Park,Margaret,Sales Support Agent,2.0,1947-09-19,2003-05-03,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03,2003-10-17,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [ ]:
connection.close()

In [ ]:
pd.read_sql_query('SELECT * FROM employees2;', conn).head()

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [ ]:
pd.DataFrame().to_sql('employees2',
                      conn,
                      if_exists='replace')
pd.read_sql_query('SELECT * FROM employees2;', conn).head()

Empty DataFrame
Columns: [index]
Index: []

In [ ]:
df.to_sql('employees2',
          conn,
          if_exists='replace')

In [ ]:
pd.read_sql_query('SELECT * FROM employees2;', conn).head()

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [ ]:
conn.close()

LESSON 12

In [ ]:
import numpy as np
import pandas as pd
import sqlite3

# create a new connection to a db in memory
conn = sqlite3.connect(':memory:')

# create a cursor
c = conn.cursor()

# restore the given van_crime_2003.sql dump
c.executescript(open('van_crime_2003.sql', 'r').read())

van_crimes_df = pd.read_sql('SELECT * FROM van_crimes WHERE hour > 14', conn)

late_crimes = van_crimes_df.loc[van_crimes_df['HOUR'] > 18]

dangerous_month_crimes = van_crimes_df.loc[:, 'MONTH'].value_counts().head(1)

In [ ]:
van_crimes_df.head()

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y
0,Theft from Vehicle,2003,11,17.0,16.0,0.0,56XX OAK ST,South Cambie,490682.32,5453536.96
1,Theft from Vehicle,2003,12,28.0,16.0,45.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
2,Theft from Vehicle,2003,12,12.0,15.0,30.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
3,Theft from Vehicle,2003,11,5.0,16.0,30.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
4,Theft of Vehicle,2003,9,2.0,21.0,0.0,20XX E 28TH AVE,Kensington-Cedar Cottage,495267.03,5454779.05

In [ ]:
late_crimes.head()

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y
4,Theft of Vehicle,2003,9,2.0,21.0,0.0,20XX E 28TH AVE,Kensington-Cedar Cottage,495267.03,5454779.05
5,Theft from Vehicle,2003,9,27.0,22.0,30.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
6,Theft from Vehicle,2003,12,17.0,21.0,0.0,31XX WILLOW ST,Fairview,491115.72,5456039.96
7,Theft from Vehicle,2003,9,1.0,20.0,10.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
8,Theft from Vehicle,2003,8,17.0,19.0,0.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36

In [ ]:
dangerous_month_crimes.head()

6    17
Name: MONTH, dtype: int64

LESSON 13

In [ ]:
import numpy as np
import pandas as pd
import sqlite3

# create a new connection to a db in memory
conn = sqlite3.connect(':memory:')

# create a cursor
c = conn.cursor()

# restore the given van_crime_2003.sql dump
c.executescript(open('van_crime_2003.sql', 'r').read())

van_crimes_df = pd.read_sql('''SELECT TYPE, MONTH, DAY, NEIGHBOURHOOD
                            FROM van_crimes WHERE NEIGHBOURHOOD IN ("Stanley Park", "West End")''', conn)

crime_types_count = van_crimes_df['TYPE'].value_counts()

In [ ]:
van_crimes_df.head()

                 TYPE  MONTH   DAY NEIGHBOURHOOD
0  Theft from Vehicle     12  30.0  Stanley Park
1  Theft from Vehicle     12  28.0  Stanley Park
2  Theft from Vehicle     12  12.0  Stanley Park
3  Theft from Vehicle     12  12.0  Stanley Park
4  Theft from Vehicle     11   5.0  Stanley Park

In [ ]:
crime_types_count

Theft from Vehicle                   31
Break and Enter Residential/Other    15
Theft of Vehicle                     11
Mischief                              7
Name: TYPE, dtype: int64

LESSON 14

In [ ]:
import numpy as np
import pandas as pd
import sqlite3

# create a new connection to a db in memory
conn = sqlite3.connect(':memory:')

# create a cursor
c = conn.cursor()

# restore the given cryptos.sql dump
c.executescript(open('cryptos.sql', 'r').read())

crypto_df = pd.read_sql('''SELECT cryptocoins_cryptocurrency.name AS coin_name, cryptocoins_exchange.name AS exchange, symbol, price_usd, percent_change_7d
                            FROM cryptocoins_cryptocurrency
                            JOIN cryptocoins_exchange
                            ON cryptocoins_cryptocurrency.exchange_id = cryptocoins_exchange.id''', conn)

weekly_change_df = crypto_df.sort_values('percent_change_7d', ascending=False)

In [ ]:
crypto_df.head()

      coin_name  exchange symbol  price_usd  percent_change_7d
0       Bitcoin  Bitstamp    BTC    8707.37              -5.91
1      Ethereum  Bitstamp    ETH     186.50              -0.66
2           XRP  Bitstamp    XRP       0.27              -8.22
3  Bitcoin Cash   Binance    BCH     278.92              -4.76
4        Tether  Bitstamp   USDT       1.01               0.45

In [ ]:
weekly_change_df

        coin_name  exchange symbol  price_usd  percent_change_7d
65  DxChain Token      OKEx     DX       0.00              89.14
39         MINDOL  Bitstamp    MIN       1.36              72.90
74          Seele  Bitstamp  SEELE       0.11              39.59
61         Komodo  Poloniex    KMD       0.86              22.75
26        VeChain      OKEx    VET       0.01              21.49
..            ...       ...    ...        ...                ...
35  Insight Chain  Bitstamp    INB       0.64             -13.37
57          Bytom      OKEx    BTM       0.11             -13.42
64      Silverway  Poloniex    SLV       0.95             -13.84
63        EDUCare      OKEx    EKT       0.10             -14.31
59           LUNA  Poloniex   LUNA       0.37             -17.84

[100 rows x 5 columns]

LESSON 15

In [ ]:
import requests

api_url = "http://api.citybik.es/v2/networks"

In [ ]:
req = requests.get(api_url)

req

In [ ]:
req.ok

True

In [ ]:
req.status_code

200

In [ ]:
req.text

'{"networks":[{"company":["\\u0417\\u0410\\u041e \\u00ab\\u0421\\u0438\\u0442\\u0438\\u0411\\u0430\\u0439\\u043a\\u00bb"],"href":"/v2/networks/velobike-moscow","id":"velobike-moscow","location":{"city":"Moscow","country":"RU","latitude":55.75,"longitude":37.616667},"name":"Velobike"},{"company":["Gobike A/S"],"href":"/v2/networks/bycyklen","id":"bycyklen","location":{"city":"Copenhagen","country":"DK","latitude":55.673582,"longitude":12.564984},"name":"Bycyklen"},{"company":["Gobike A/S"],"href":"/v2/networks/nu-connect","id":"nu-connect","location":{"city":"Utrecht","country":"NL","latitude":52.117,"longitude":5.067},"name":"Nu-Connect"},{"company":["Urban Infrastructure Partner"],"href":"/v2/networks/baerum-bysykkel","id":"baerum-bysykkel","location":{"city":"B\\u00e6rum","country":"NO","latitude":59.89455,"longitude":10.546343},"name":"Bysykkel"},{"company":["Gobike A/S"],"href":"/v2/networks/bysykkelen","id":"bysykkelen","location":{"city":"Stavanger","country":"NO","latitude":58.969975,"longitude":5.733107},"name":"Bysykkelen"},{"company":["Domoblue"],"href":"/v2/networks/onroll-a-rua","id":"onroll-a-rua","location":{"city":"A R\\u00faa","country":"ES","latitude":42.392049,"longitude":-7.114634},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-albacete","id":"onroll-albacete","location":{"city":"Albacete","country":"ES","latitude":38.98913,"longitude":-1.858485},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-alhama-de-murcia","id":"onroll-alhama-de-murcia","location":{"city":"Alhama de Murcia","country":"ES","latitude":37.849831,"longitude":-1.424891},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-almunecar","id":"onroll-almunecar","location":{"city":"Almu\\u00f1\\u00e9car","country":"ES","latitude":36.735789,"longitude":-3.688828},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-antequera","id":"onroll-antequera","location":{"city":"Antequera","country":"ES","latitude":37.018427,"longitude":-4.563775},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-aranda-de-duero","id":"onroll-aranda-de-duero","location":{"city":"Aranda de Duero","country":"ES","latitude":41.667601,"longitude":-3.689526},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-aranjuez","id":"onroll-aranjuez","location":{"city":"Aranjuez","country":"ES","latitude":40.03097,"longitude":-3.605742},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-badajoz","id":"onroll-badajoz","location":{"city":"Badajoz","country":"ES","latitude":38.873627,"longitude":-6.99451},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-baeza","id":"onroll-baeza","location":{"city":"Baeza","country":"ES","latitude":37.99537,"longitude":-3.468248},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-benidorm","id":"onroll-benidorm","location":{"city":"Benidorm","country":"ES","latitude":38.541251,"longitude":-0.126808},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-blanca","id":"onroll-blanca","location":{"city":"Blanca","country":"ES","latitude":38.178195,"longitude":-1.372402},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-cieza","id":"onroll-cieza","location":{"city":"Cieza","country":"ES","latitude":38.239139,"longitude":-1.417262},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-don-benito-villanueva","id":"onroll-don-benito-villanueva","location":{"city":"Don Benito - Villanueva","country":"ES","latitude":38.964699,"longitude":-5.829693},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-el-campello","id":"onroll-el-campello","location":{"city":"El Campello","country":"ES","latitude":38.419616,"longitude":-0.398388},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-elche","id":"onroll-elche","location":{"city":"Elche","country":"ES","latitude":38.2668,"longitude":-0.696217},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-guadalajara","id":"onroll-guadalajara","location":{"city":"Guadalajara","country":"ES","latitude":40.633021,"longitude":-3.166097},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-jaen","id":"onroll-jaen","location":{"city":"Ja\\u00e9n","country":"ES","latitude":37.777738,"longitude":-3.790758},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-lalin","id":"onroll-lalin","location":{"city":"Lal\\u00edn","country":"ES","latitude":42.658626,"longitude":-8.114976},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-las-palmas","id":"onroll-las-palmas","location":{"city":"Las Palmas de Gran Canaria","country":"ES","latitude":28.124302,"longitude":-15.425994},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-montilla","id":"onroll-montilla","location":{"city":"Montilla","country":"ES","latitude":37.584151,"longitude":-4.641359},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-novelda","id":"onroll-novelda","location":{"city":"Novelda","country":"ES","latitude":38.386447,"longitude":-0.767134},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-mula","id":"onroll-mula","location":{"city":"Mula","country":"ES","latitude":38.040805,"longitude":-1.497451},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-o-barco","id":"onroll-o-barco","location":{"city":"O Barco","country":"ES","latitude":42.413993,"longitude":-6.982913},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-palencia","id":"onroll-palencia","location":{"city":"Palencia","country":"ES","latitude":42.005639,"longitude":-4.527022},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-paiporta","id":"onroll-paiporta","location":{"city":"Paiporta","country":"ES","latitude":39.427609,"longitude":-0.416876},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-pinto","id":"onroll-pinto","location":{"city":"Pinto","country":"ES","latitude":40.245741,"longitude":-3.698611},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-priego-de-cordoba","id":"onroll-priego-de-cordoba","location":{"city":"Priego de C\\u00f3rdoba","country":"ES","latitude":37.440517,"longitude":-4.201188},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-puerto-lumbreras","id":"onroll-puerto-lumbreras","location":{"city":"Puerto Lumbreras","country":"ES","latitude":37.556652,"longitude":-1.811508},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-puertollano","id":"onroll-puertollano","location":{"city":"Puertollano","country":"ES","latitude":38.691396,"longitude":-4.107794},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-redondela","id":"onroll-redondela","location":{"city":"Redondela","country":"ES","latitude":42.299964,"longitude":-8.615428},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-salamanca","id":"onroll-salamanca","location":{"city":"Salamanca","country":"ES","latitude":40.966771,"longitude":-5.665432},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-san-javier","id":"onroll-san-javier","location":{"city":"San Javier","country":"ES","latitude":37.783704,"longitude":-0.808097},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-san-pedro","id":"onroll-san-pedro","location":{"city":"San Pedro del Pinatar","country":"ES","latitude":37.827578,"longitude":-0.783944},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-sant-joan","id":"onroll-sant-joan","location":{"city":"Sant Joan d\'Alacant","country":"ES","latitude":38.399839,"longitude":-0.434522},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-segovia","id":"onroll-segovia","location":{"city":"Segovia","country":"ES","latitude":40.941941,"longitude":-4.112397},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-soria","id":"onroll-soria","location":{"city":"Soria","country":"ES","latitude":41.763653,"longitude":-2.467069},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-talavera","id":"onroll-talavera","location":{"city":"Talavera de la Reina","country":"ES","latitude":39.961829,"longitude":-4.830319},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-ubeda","id":"onroll-ubeda","location":{"city":"\\u00dabeda","country":"ES","latitude":38.011463,"longitude":-3.373276},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-universidad-de-granada","id":"onroll-universidad-de-granada","location":{"city":"Universidad de Granada, Granada","country":"ES","latitude":37.182438,"longitude":-3.604219},"name":"Onroll"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/bicincitta-siena","id":"bicincitta-siena","location":{"city":"Siena","country":"IT","latitude":43.3186,"longitude":11.3306},"name":"Bicincitt\\u00e0","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=202"},{"company":["Domoblue"],"href":"/v2/networks/onroll-via-verde","id":"onroll-via-verde","location":{"city":"Noia - Portosin - Porto do Son","country":"ES","latitude":42.768127,"longitude":-8.908513},"name":"Onroll Via Verde"},{"company":["Domoblue"],"href":"/v2/networks/onroll-villaquilambre","id":"onroll-villaquilambre","location":{"city":"Villaquilambre","country":"ES","latitude":42.642358,"longitude":-5.535311},"name":"Onroll"},{"company":["Domoblue"],"href":"/v2/networks/onroll-vinaros","id":"onroll-vinaros","location":{"city":"Vinar\\u00f2s","country":"ES","latitude":40.468258,"longitude":0.466972},"name":"Onroll"},{"company":["Cyclopolis Systems"],"href":"/v2/networks/cyclopolis-maroussi","id":"cyclopolis-maroussi","location":{"city":"Maroussi","country":"GR","latitude":38.0568722388,"longitude":23.8083299536},"name":"Cyclopolis"},{"company":["Groundwork","Slough Borough Council","ITS"],"href":"/v2/networks/cycle-hire-slough","id":"cycle-hire-slough","location":{"city":"Slough","country":"GB","latitude":51.51135,"longitude":-0.591562},"name":"Cycle Hire"},{"company":["Cyclopolis Systems"],"href":"/v2/networks/cyclopolis-nafplio","id":"cyclopolis-nafplio","location":{"city":"Maroussi","country":"GR","latitude":37.5639397319,"longitude":22.8093402872},"name":"Cyclopolis"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/bicincitta-parco-dei-colli-di-bergamo","id":"bicincitta-parco-dei-colli-di-bergamo","location":{"city":"Parco dei Colli di Bergamo","country":"IT","latitude":45.72295637032245,"longitude":9.649230073016383},"name":"Bicincitt\\u00e0","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=203"},{"company":["Cyclopolis Systems"],"href":"/v2/networks/cyclopolis-aigialeia","id":"cyclopolis-aigialeia","location":{"city":"Maroussi","country":"GR","latitude":38.2511101325,"longitude":22.0821570196},"name":"Cyclopolis"},{"company":["Cyclopolis Systems"],"href":"/v2/networks/cyclopolis-marathon","id":"cyclopolis-marathon","location":{"city":"Marathon","country":"GR","latitude":38.0855680022,"longitude":23.9776389963},"name":"Cyclopolis"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/bicincitta-mantova","id":"bicincitta-mantova","location":{"city":"Mantova","country":"IT","latitude":45.15866370764634,"longitude":10.783718973016335},"name":"Bicincitt\\u00e0","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=204"},{"company":["Cyclopolis Systems"],"href":"/v2/networks/cyclopolis-neasmyrni","id":"cyclopolis-neasmyrni","location":{"city":"\\u039dea Smyrni","country":"GR","latitude":37.9381,"longitude":23.7126},"name":"Cyclopolis"},{"company":["Cyclopolis Systems"],"href":"/v2/networks/cyclopolis-moschatotavros","id":"cyclopolis-moschatotavros","location":{"city":"\\u039coschato-Tavros","country":"GR","latitude":37.9538991434,"longitude":23.6824746661},"name":"Cyclopolis"},{"company":["Cyclopolis Systems"],"href":"/v2/networks/cyclopolis-arxaiaolympia","id":"cyclopolis-arxaiaolympia","location":{"city":"\\u0391rxaia Olympia","country":"GR","latitude":37.6419700934,"longitude":21.6247265179},"name":"Cyclopolis"},{"company":["Cyclopolis Systems"],"href":"/v2/networks/cyclopolis-kiato","id":"cyclopolis-kiato","location":{"city":"K\\u03b9ato","country":"GR","latitude":38.0132674508,"longitude":22.7493819902},"name":"Cyclopolis"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/bicincitta-assemini","id":"bicincitta-assemini","location":{"city":"Assemini","country":"IT","latitude":39.28956306007679,"longitude":9.006601555294765},"name":"Bicincitt\\u00e0","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=205"},{"company":["Cyclopolis Systems"],"href":"/v2/networks/cyclopolis-rhodes","id":"cyclopolis-rhodes","location":{"city":"Rhodes","country":"GR","latitude":36.4509118,"longitude":28.2246966},"name":"Cyclopolis"},{"company":["Cyclopolis Systems"],"href":"/v2/networks/cyclopolis-florina","id":"cyclopolis-florina","location":{"city":"Florina","country":"GR","latitude":40.8016111,"longitude":21.4245222},"name":"Cyclopolis"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/bicincitta-tortoli","id":"bicincitta-tortoli","location":{"city":"Tortol\\u00ec","country":"IT","latitude":39.92664489852196,"longitude":9.654953570777934},"name":"Bicincitt\\u00e0","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=206"},{"company":["Cyclopolis Systems"],"href":"/v2/networks/cyclopolis-limnos","id":"cyclopolis-limnos","location":{"city":"Limnos","country":"GR","latitude":39.8747861,"longitude":25.0586722},"name":"Cyclopolis"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/bicincitta-gaeta","id":"bicincitta-gaeta","location":{"city":"Gaeta","country":"IT","latitude":41.209620965538036,"longitude":13.584335125656139},"name":"Bicincitt\\u00e0","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=207"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/bicincitta-borgarello","id":"bicincitta-borgarello","location":{"city":"Borgarello","country":"IT","latitude":45.23963753440171,"longitude":9.136150475640875},"name":"Bicincitt\\u00e0","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=208"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/bicincitta-pizzighettone-formigara","id":"bicincitta-pizzighettone-formigara","location":{"city":"Pizzighettone e Formigara","country":"IT","latitude":45.186748819167434,"longitude":9.778087948479424},"name":"Bicincitt\\u00e0","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=209"},{"company":["The National Transport Authority"],"href":"/v2/networks/cork","id":"cork","location":{"city":"Cork","country":"IE","latitude":51.893604,"longitude":-8.494174},"name":"Coca-Cola Zero\\u00ae Bikes"},{"company":["The National Transport Authority"],"href":"/v2/networks/limerick","id":"limerick","location":{"city":"Limerick","country":"IE","latitude":52.668746,"longitude":-8.627809},"name":"Coca-Cola Zero\\u00ae Bikes"},{"company":["BTS Group Holdings"],"href":"/v2/networks/punpunbikeshare","id":"punpunbikeshare","location":{"city":"Bangkok","country":"TH","latitude":13.75,"longitude":100.516667},"name":"Pun Pun Bike Share"},{"company":["The National Transport Authority"],"href":"/v2/networks/galway","id":"galway","location":{"city":"Galway","country":"IE","latitude":53.2783491544,"longitude":-9.05069143207},"name":"Coca-Cola Zero\\u00ae Bikes"},{"company":["Bike U Sp. z o.o."],"href":"/v2/networks/bbbike","id":"bbbike","location":{"city":"Bielsko-Bia\\u0142a","country":"PL","latitude":49.8225,"longitude":19.044444},"name":"BBBike"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/bicincitta-montecatini-terme","id":"bicincitta-montecatini-terme","location":{"city":"Montecatini Terme","country":"IT","latitude":43.88362791665083,"longitude":10.764385656591799},"name":"Bicincitt\\u00e0","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=210"},{"company":["Bike U Sp. z o.o."],"href":"/v2/networks/bikeu-bra","id":"bikeu-bra","location":{"city":"Bydgoszcz","country":"PL","latitude":53.12193,"longitude":18.00038},"name":"Bydgoski rower aglomeracyjny"},{"company":["PBSC","Serco Group plc"],"href":"/v2/networks/santander-cycles","id":"santander-cycles","location":{"city":"London","country":"GB","latitude":51.51121389999999,"longitude":-0.1198244},"name":"Santander Cycles"},{"company":["PBSC","Alta Bicycle Share, Inc"],"gbfs_href":"https://asp.publicbikesystem.net/ube/gbfs/v1/gbfs.json","href":"/v2/networks/we-cycle","id":"we-cycle","location":{"city":"Aspen, CO","country":"US","latitude":39.194951,"longitude":-106.837002},"name":"WE-cycle"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/bicincitta-carrara","id":"bicincitta-carrara","location":{"city":"Carrara","country":"IT","latitude":44.07731805550891,"longitude":10.097172450401331},"name":"Bicincitt\\u00e0","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=211"},{"company":["PBSC","Alta Bicycle Share, Inc"],"href":"/v2/networks/wowcycle-reykjavik","id":"wowcycle-reykjavik","location":{"city":"Reykjav\\u00edk","country":"IS","latitude":64.128288,"longitude":-21.827774},"name":"WOW Citybike"},{"company":["Transparenzportal Hamburg"],"href":"/v2/networks/stadtrad-hamburg","id":"stadtrad-hamburg","license":{"name":"Data licence Germany \\u2013 attribution \\u2013 version 2.0","url":"https://www.govdata.de/dl-de/by-2-0"},"location":{"city":"Hamburg","country":"DE","latitude":53.57532,"longitude":10.01534},"name":"StadtRAD Hamburg\'"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/tigullionbike","id":"tigullionbike","location":{"city":"Sestri Levante - Lavagna","country":"IT","latitude":44.272554,"longitude":9.395714},"name":"Tigullionbike","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=80"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/arbike","id":"arbike","location":{"city":"Arezzo","country":"IT","latitude":43.473333,"longitude":11.87},"name":"ARbike","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=84"},{"company":["Velobike.kz, LLP","Smoove"],"href":"/v2/networks/velobike","id":"velobike","location":{"city":"Astana","country":"KZ","latitude":51.166667,"longitude":71.416667},"name":"Velobike"},{"company":null,"ebikes":true,"gbfs_href":"https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/gbfs.json","href":"/v2/networks/velib","id":"velib","license":{"name":"OPEN LICENCE 2.0","url":"etalab.gouv.fr/wp-content/uploads/2018/11/open-licence.pdf"},"location":{"city":"Paris","country":"FR","latitude":48.856614,"longitude":2.3522219},"name":"Velib\' M\\u00e9trop\\u00f4le"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/ascoli-piceno","id":"ascoli-piceno","location":{"city":"Ascoli Piceno","country":"IT","latitude":42.85,"longitude":13.583333},"name":"Ascoli Piceno","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=73"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/bigi","id":"bigi","location":{"city":"Bergamo","country":"IT","latitude":45.695,"longitude":9.67},"name":"BiGi","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=133"},{"company":["ICNITA S.L."],"href":"/v2/networks/girocleta","id":"girocleta","location":{"city":"Girona","country":"ES","latitude":41.9794005,"longitude":2.8214264},"name":"Girocleta"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/alba","id":"alba","location":{"city":"Alba","country":"IT","latitude":44.716667,"longitude":8.083333},"name":"Alba","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=139"},{"company":["ClearChannel"],"ebikes":true,"href":"/v2/networks/bikemi","id":"bikemi","location":{"city":"Milano","country":"IT","latitude":45.4654542,"longitude":9.186516},"name":"BikeMi"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/biella","id":"biella","location":{"city":"Biella","country":"IT","latitude":45.5775,"longitude":8.051111},"name":"Biella","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=112"},{"company":["Comunicare S.r.l."],"href":"/v2/networks/chivasso","id":"chivasso","location":{"city":"Chivasso","

In [ ]:
pd.read_json(req.text).head()

ValueError: ignored

In [ ]:
json_dict = req.json()

json_dict

{'networks': [{'company': ['ЗАО «СитиБайк»'],
   'href': '/v2/networks/velobike-moscow',
   'id': 'velobike-moscow',
   'location': {'city': 'Moscow',
    'country': 'RU',
    'latitude': 55.75,
    'longitude': 37.616667},
   'name': 'Velobike'},
  {'company': ['Gobike A/S'],
   'href': '/v2/networks/bycyklen',
   'id': 'bycyklen',
   'location': {'city': 'Copenhagen',
    'country': 'DK',
    'latitude': 55.673582,
    'longitude': 12.564984},
   'name': 'Bycyklen'},
  {'company': ['Gobike A/S'],
   'href': '/v2/networks/nu-connect',
   'id': 'nu-connect',
   'location': {'city': 'Utrecht',
    'country': 'NL',
    'latitude': 52.117,
    'longitude': 5.067},
   'name': 'Nu-Connect'},
  {'company': ['Urban Infrastructure Partner'],
   'href': '/v2/networks/baerum-bysykkel',
   'id': 'baerum-bysykkel',
   'location': {'city': 'Bærum',
    'country': 'NO',
    'latitude': 59.89455,
    'longitude': 10.546343},
   'name': 'Bysykkel'},
  {'company': ['Gobike A/S'],
   'href': '/v2/networks/bysykkelen',
   'id': 'bysykkelen',
   'location': {'city': 'Stavanger',
    'country': 'NO',
    'latitude': 58.969975,
    'longitude': 5.733107},
   'name': 'Bysykkelen'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-a-rua',
   'id': 'onroll-a-rua',
   'location': {'city': 'A Rúa',
    'country': 'ES',
    'latitude': 42.392049,
    'longitude': -7.114634},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-albacete',
   'id': 'onroll-albacete',
   'location': {'city': 'Albacete',
    'country': 'ES',
    'latitude': 38.98913,
    'longitude': -1.858485},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-alhama-de-murcia',
   'id': 'onroll-alhama-de-murcia',
   'location': {'city': 'Alhama de Murcia',
    'country': 'ES',
    'latitude': 37.849831,
    'longitude': -1.424891},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-almunecar',
   'id': 'onroll-almunecar',
   'location': {'city': 'Almuñécar',
    'country': 'ES',
    'latitude': 36.735789,
    'longitude': -3.688828},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-antequera',
   'id': 'onroll-antequera',
   'location': {'city': 'Antequera',
    'country': 'ES',
    'latitude': 37.018427,
    'longitude': -4.563775},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-aranda-de-duero',
   'id': 'onroll-aranda-de-duero',
   'location': {'city': 'Aranda de Duero',
    'country': 'ES',
    'latitude': 41.667601,
    'longitude': -3.689526},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-aranjuez',
   'id': 'onroll-aranjuez',
   'location': {'city': 'Aranjuez',
    'country': 'ES',
    'latitude': 40.03097,
    'longitude': -3.605742},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-badajoz',
   'id': 'onroll-badajoz',
   'location': {'city': 'Badajoz',
    'country': 'ES',
    'latitude': 38.873627,
    'longitude': -6.99451},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-baeza',
   'id': 'onroll-baeza',
   'location': {'city': 'Baeza',
    'country': 'ES',
    'latitude': 37.99537,
    'longitude': -3.468248},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-benidorm',
   'id': 'onroll-benidorm',
   'location': {'city': 'Benidorm',
    'country': 'ES',
    'latitude': 38.541251,
    'longitude': -0.126808},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-blanca',
   'id': 'onroll-blanca',
   'location': {'city': 'Blanca',
    'country': 'ES',
    'latitude': 38.178195,
    'longitude': -1.372402},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-cieza',
   'id': 'onroll-cieza',
   'location': {'city': 'Cieza',
    'country': 'ES',
    'latitude': 38.239139,
    'longitude': -1.417262},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-don-benito-villanueva',
   'id': 'onroll-don-benito-villanueva',
   'location': {'city': 'Don Benito - Villanueva',
    'country': 'ES',
    'latitude': 38.964699,
    'longitude': -5.829693},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-el-campello',
   'id': 'onroll-el-campello',
   'location': {'city': 'El Campello',
    'country': 'ES',
    'latitude': 38.419616,
    'longitude': -0.398388},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-elche',
   'id': 'onroll-elche',
   'location': {'city': 'Elche',
    'country': 'ES',
    'latitude': 38.2668,
    'longitude': -0.696217},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-guadalajara',
   'id': 'onroll-guadalajara',
   'location': {'city': 'Guadalajara',
    'country': 'ES',
    'latitude': 40.633021,
    'longitude': -3.166097},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-jaen',
   'id': 'onroll-jaen',
   'location': {'city': 'Jaén',
    'country': 'ES',
    'latitude': 37.777738,
    'longitude': -3.790758},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-lalin',
   'id': 'onroll-lalin',
   'location': {'city': 'Lalín',
    'country': 'ES',
    'latitude': 42.658626,
    'longitude': -8.114976},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-las-palmas',
   'id': 'onroll-las-palmas',
   'location': {'city': 'Las Palmas de Gran Canaria',
    'country': 'ES',
    'latitude': 28.124302,
    'longitude': -15.425994},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-montilla',
   'id': 'onroll-montilla',
   'location': {'city': 'Montilla',
    'country': 'ES',
    'latitude': 37.584151,
    'longitude': -4.641359},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-novelda',
   'id': 'onroll-novelda',
   'location': {'city': 'Novelda',
    'country': 'ES',
    'latitude': 38.386447,
    'longitude': -0.767134},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-mula',
   'id': 'onroll-mula',
   'location': {'city': 'Mula',
    'country': 'ES',
    'latitude': 38.040805,
    'longitude': -1.497451},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-o-barco',
   'id': 'onroll-o-barco',
   'location': {'city': 'O Barco',
    'country': 'ES',
    'latitude': 42.413993,
    'longitude': -6.982913},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-palencia',
   'id': 'onroll-palencia',
   'location': {'city': 'Palencia',
    'country': 'ES',
    'latitude': 42.005639,
    'longitude': -4.527022},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-paiporta',
   'id': 'onroll-paiporta',
   'location': {'city': 'Paiporta',
    'country': 'ES',
    'latitude': 39.427609,
    'longitude': -0.416876},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-pinto',
   'id': 'onroll-pinto',
   'location': {'city': 'Pinto',
    'country': 'ES',
    'latitude': 40.245741,
    'longitude': -3.698611},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-priego-de-cordoba',
   'id': 'onroll-priego-de-cordoba',
   'location': {'city': 'Priego de Córdoba',
    'country': 'ES',
    'latitude': 37.440517,
    'longitude': -4.201188},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-puerto-lumbreras',
   'id': 'onroll-puerto-lumbreras',
   'location': {'city': 'Puerto Lumbreras',
    'country': 'ES',
    'latitude': 37.556652,
    'longitude': -1.811508},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-puertollano',
   'id': 'onroll-puertollano',
   'location': {'city': 'Puertollano',
    'country': 'ES',
    'latitude': 38.691396,
    'longitude': -4.107794},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-redondela',
   'id': 'onroll-redondela',
   'location': {'city': 'Redondela',
    'country': 'ES',
    'latitude': 42.299964,
    'longitude': -8.615428},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-salamanca',
   'id': 'onroll-salamanca',
   'location': {'city': 'Salamanca',
    'country': 'ES',
    'latitude': 40.966771,
    'longitude': -5.665432},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-san-javier',
   'id': 'onroll-san-javier',
   'location': {'city': 'San Javier',
    'country': 'ES',
    'latitude': 37.783704,
    'longitude': -0.808097},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-san-pedro',
   'id': 'onroll-san-pedro',
   'location': {'city': 'San Pedro del Pinatar',
    'country': 'ES',
    'latitude': 37.827578,
    'longitude': -0.783944},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-sant-joan',
   'id': 'onroll-sant-joan',
   'location': {'city': "Sant Joan d'Alacant",
    'country': 'ES',
    'latitude': 38.399839,
    'longitude': -0.434522},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-segovia',
   'id': 'onroll-segovia',
   'location': {'city': 'Segovia',
    'country': 'ES',
    'latitude': 40.941941,
    'longitude': -4.112397},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-soria',
   'id': 'onroll-soria',
   'location': {'city': 'Soria',
    'country': 'ES',
    'latitude': 41.763653,
    'longitude': -2.467069},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-talavera',
   'id': 'onroll-talavera',
   'location': {'city': 'Talavera de la Reina',
    'country': 'ES',
    'latitude': 39.961829,
    'longitude': -4.830319},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-ubeda',
   'id': 'onroll-ubeda',
   'location': {'city': 'Úbeda',
    'country': 'ES',
    'latitude': 38.011463,
    'longitude': -3.373276},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-universidad-de-granada',
   'id': 'onroll-universidad-de-granada',
   'location': {'city': 'Universidad de Granada, Granada',
    'country': 'ES',
    'latitude': 37.182438,
    'longitude': -3.604219},
   'name': 'Onroll'},
  {'company': ['Comunicare S.r.l.'],
   'href': '/v2/networks/bicincitta-siena',
   'id': 'bicincitta-siena',
   'location': {'city': 'Siena',
    'country': 'IT',
    'latitude': 43.3186,
    'longitude': 11.3306},
   'name': 'Bicincittà',
   'source': 'https://www.bicincitta.com/frmLeStazioni.aspx?ID=202'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-via-verde',
   'id': 'onroll-via-verde',
   'location': {'city': 'Noia - Portosin - Porto do Son',
    'country': 'ES',
    'latitude': 42.768127,
    'longitude': -8.908513},
   'name': 'Onroll Via Verde'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-villaquilambre',
   'id': 'onroll-villaquilambre',
   'location': {'city': 'Villaquilambre',
    'country': 'ES',
    'latitude': 42.642358,
    'longitude': -5.535311},
   'name': 'Onroll'},
  {'company': ['Domoblue'],
   'href': '/v2/networks/onroll-vinaros',
   'id': 'onroll-vinaros',
   'location': {'city': 'Vinaròs',
    'country': 'ES',
    'latitude': 40.468258,
    'longitude': 0.466972},
   'name': 'Onroll'},
  {'company': ['Cyclopolis Systems'],
   'href': '/v2/networks/cyclopolis-maroussi',
   'id': 'cyclopolis-maroussi',
   'location': {'city': 'Maroussi',
    'country': 'GR',
    'latitude': 38.0568722388,
    'longitude': 23.8083299536},
   'name': 'Cyclopolis'},
  {'company': ['Groundwork', 'Slough Borough Council', 'ITS'],
   'href': '/v2/networks/cycle-hire-slough',
   'id': 'cycle-hire-slough',
   'location': {'city': 'Slough',
    'country': 'GB',
    'latitude': 51.51135,
    'longitude': -0.591562},
   'name': 'Cycle Hire'},
  {'company': ['Cyclopolis Systems'],
   'href': '/v2/networks/cyclopolis-nafplio',
   'id': 'cyclopolis-nafplio',
   'location': {'city': 'Maroussi',
    'country': 'GR',
    'latitude': 37.5639397319,
    'longitude': 22.8093402872},
   'name': 'Cyclopolis'},
  {'company': ['Comunicare S.r.l.'],
   'href': '/v2/networks/bicincitta-parco-dei-colli-di-bergamo',
   'id': 'bicincitta-parco-dei-colli-di-bergamo',
   'location': {'city': 'Parco dei Colli di Bergamo',
    'country': 'IT',
    'latitude': 45.72295637032245,
    'longitude': 9.649230073016383},
   'name': 'Bicincittà',
   'source': 'https://www.bicincitta.com/frmLeStazioni.aspx?ID=203'},
  {'company': ['Cyclopolis Systems'],
   'href': '/v2/networks/cyclopolis-aigialeia',
   'id': 'cyclopolis-aigialeia',
   'location': {'city': 'Maroussi',
    'country': 'GR',
    'latitude': 38.2511101325,
    'longitude': 22.0821570196},
   'name': 'Cyclopolis'},
  {'company': ['Cyclopolis Systems'],
   'href': '/v2/networks/cyclopolis-marathon',
   'id': 'cyclopolis-marathon',
   'location': {'city': 'Marathon',
    'country': 'GR',
    'latitude': 38.0855680022,
    'longitude': 23.9776389963},
   'name': 'Cyclopolis'},
  {'company': ['Comunicare S.r.l.'],
   'href': '/v2/networks/bicincitta-mantova',
   'id': 'bicincitta-mantova',
   'location': {'city': 'Mantova',
    'country': 'IT',
    'latitude': 45.15866370764634,
    'longitude': 10.783718973016335},
   'name': 'Bicincittà',
   'source': 'https://www.bicincitta.com/frmLeStazioni.aspx?ID=204'},
  {'company': ['Cyclopolis Systems'],
   'href': '/v2/networks/cyclopolis-neasmyrni',
   'id': 'cyclopolis-neasmyrni',
   'location': {'city': 'Νea Smyrni',
    'country': 'GR',
    'latitude': 37.9381,
    'longitude': 23.7126},
   'name': 'Cyclopolis'},
  {'company': ['Cyclopolis Systems'],
   'href': '/v2/networks/cyclopolis-moschatotavros',
   'id': 'cyclopolis-moschatotavros',
   'location': {'city': 'Μoschato-Tavros',
    'country': 'GR',
    'latitude': 37.9538991434,
    'longitude': 23.6824746661},
   'name': 'Cyclopolis'},
  {'company': ['Cyclopolis Systems'],
   'href': '/v2/networks/cyclopolis-arxaiaolympia',
   'id': 'cyclopolis-arxaiaolympia',
   'location': {'city': 'Αrxaia Olympia',
    'country': 'GR',
    'latitude': 37.6419700934,
    'longitude': 21.6247265179},
   'name': 'Cyclopolis'},
  {'company': ['Cyclopolis Systems'],
   'href': '/v2/networks/cyclopolis-kiato',
   'id': 'cyclopolis-kiato',
   'location': {'city': 'Kιato',
    'country': 'GR',
    'latitude': 38.0132674508,
    'longitude': 22.7493819902},
   'name': 'Cyclopolis'},
  {'company': ['Comunicare S.r.l.'],
   'href': '/v2/networks/bicincitta-assemini',
   'id': 'bicincitta-assemini',
   'location': {'city': 'Assemini',
    'country': 'IT',
    'latitude': 39.28956306007679,
    'longitude': 9.006601555294765},
   'name': 'Bicincittà',
   'source': 'https://www.bicincitta.com/frmLeStazioni.aspx?ID=205'},
  {'company': ['Cyclopolis Systems'],
   'href': '/v2/networks/cyclopolis-rhodes',
   'id': 'cyclopolis-rhodes',
   'location': {'city': 'Rhodes',
    'country': 'GR',
    'latitude': 36.4509118,
    'longitude': 28.2246966},
   'name': 'Cyclopolis'},
  {'company': ['Cyclopolis Systems'],
   'href': '/v2/networks/cyclopolis-florina',
   'id': 'cyclopolis-florina',
   'location': {'city': 'Florina',
    'country': 'GR',
    'latitude': 40.8016111,
    'longitude': 21.4245222},
   'name': 'Cyclopolis'},
  {'company': ['Comunicare S.r.l.'],
   'href': '/v2/networks/bicincitta-tortoli',
   'id': 'bicincitta-tortoli',
   'location': {'city': 'Tortolì',
    'country': 'IT',
    'latitude': 39.92664489852196,
    'longitude': 9.654953570777934},
   'name': 'Bicincittà',
   'source': 'https://www.bicincitta.com/frmLeStazioni.aspx?ID=206'},
  {'company': ['Cyclopolis Systems'],
   'href': '/v2/networks/cyclopolis-limnos',
   'id': 'cyclopolis-limnos',
   'location': {'city': 'Limnos',
    'country': 'GR',
    'latitude': 39.8747861,
    'longitude': 25.0586722},
   'name': 'Cyclopolis'},
  {'company': ['Comunicare S.r.l.'],
   'href': '/v2/networks/bicincitta-gaeta',
   'id': 'bicincitta-gaeta',
   'location': {'city': 'Gaeta',
    'country': 'IT',
    'latitude': 41.209620965538036,
    'longitude': 13.584335125656139},
   'name': 'Bicincittà',
   'source': 'https://www.bicincitta.com/frmLeStazioni.aspx?ID=207'},
  {'company': ['Comunicare S.r.l.'],
   'href': '/v2/networks/bicincitta-borgarello',
   'id': 'bicincitta-borgarello',
   'location': {'city': 'Borgarello',
    'country': 'IT',
    'latitude': 45.23963753440171,
    'longitude': 9.136150475640875},
   'name': 'Bicincittà',
   'source': 'https://www.bicincitta.com/frmLeStazioni.aspx?ID=208'},
  {'company': ['Comunicare S.r.l.'],
   'href': '/v2/networks/bicincitta-pizzighettone-formigara',
   'id': 'bicincitta-pizzighettone-formigara',
   'location': {'city': 'Pizzighettone e Formigara',
    'country': 'IT',
    'latitude': 45.186748819167434,
    'longitude': 9.778087948479424},
   'name': 'Bicincittà',
   'source': 'https://www.bicincitta.com/frmLeStazioni.aspx?ID=209'},
  {'company': ['The National Transport Authority'],
   'href': '/v2/networks/cork',
   'id': 'cork',
   'location': {'city': 'Cork',
    'country': 'IE',
    'latitude': 51.893604,
    'longitude': -8.494174},
   'name': 'Coca-Cola Zero® Bikes'},
  {'company': ['The National Transport Authority'],
   'href': '/v2/networks/limerick',
   'id': 'limerick',
   'location': {'city': 'Limerick',
    'country': 'IE',
    'latitude': 52.668746,
    'longitude': -8.627809},
   'name': 'Coca-Cola Zero® Bikes'},
  {'company': ['BTS Group Holdings'],
   'href': '/v2/networks/punpunbikeshare',
   'id': 'punpunbikeshare',
   'location': {'city': 'Bangkok',
    'country': 'TH',
    'latitude': 13.75,
    'longitude': 100.516667},
   'name': 'Pun Pun Bike Share'},
  {'company': ['The National Transport Authority'],
   'href': '/v2/networks/galway',
   'id': 'galway',
   'location': {'city': 'Galway',
    'country': 'IE',
    'latitude': 53.2783491544,
    'longitude': -9.05069143207},
   'name': 'Coca-Cola Zero® Bikes'},
  {'company': ['Bike U Sp. z o.o.'],
   'href': '/v2/networks/bbbike',
   'id': 'bbbike',
   'location': {'city': 'Bielsko-Biała',
    'country': 'PL',
    'latitude': 49.8225,
    'longitude': 19.044444},
   'name': 'BBBike'},
  {'company': ['Comunicare S.r.l.'],
   'href': '/v2/networks/bicincitta-montecatini-terme',
   'id': 'bicincitta-montecatini-terme',
   'location': {'city': 'Montecatini Terme',
    'country': 'IT',
    'latitude': 43.88362791665083,
    'longitude': 10.764385656591799},
   'name': 'Bicincittà',
   'source': 'https://www.bicincitta.com/frmLeStazioni.aspx?ID=210'},
  {'company': ['Bike U Sp. z o.o.'],
   'href': '/v2/networks/bikeu-bra',
   'id': 'bikeu-bra',
   'location': {'city': 'Bydgoszcz',
    'country': 'PL',
    'latitude': 53.12193,
    'longitude': 18.00038},
   'name': 'Bydgoski rower aglomeracyjny'},
  {'company': ['PBSC', 'Serco Group plc'],
   'href': '/v2/networks/santander-cycles',
   'id': 'santander-cycles',
   'location': {'city': 'London',
    'country': 'GB',
    'latitude': 51.51121389999999,
    'longitude': -0.1198244},
   'name': 'Santander Cycles'},
  {'company': ['PBSC', 'Alta Bicycle Share, Inc'],
   'gbfs_href': 'https://asp.publicbikesystem.net/ube/gbfs/v1/gbfs.json',
   'href': '/v2/networks/we-cycle',
   'id': 'we-cycle',
   'location': {'city': 'Aspen, CO',
    'country': 'US',
    'latitude': 39.194951,
    'longitude': -106.837002},
   'name': 'WE-cycle'},
  {'company': ['Comunicare S.r.l.'],
   'href': '/v2/networks/bicincitta-carrara',
   'id': 'bicincitta-carrara',
   'location': {'city': 'Carrara',
    'country': 'IT',
    'latitude': 44.07731805550891,
    'longitude': 10.097172450401331},
   'name': 'Bicincittà',
   'source': 'https://www.bicincitta.com/frmLeStazioni.aspx?ID=211'},

In [ ]:
citybikes = pd.DataFrame.from_dict(json_dict['networks'])
citybikes.head()

,company,href,id,location,name,source,gbfs_href,license,ebikes
0,[ЗАО «СитиБайк»],/v2/networks/velobike-moscow,velobike-moscow,"{'city': 'Moscow', 'country': 'RU', 'latitude'...",Velobike,NaN,NaN,NaN,NaN
1,[Gobike A/S],/v2/networks/bycyklen,bycyklen,"{'city': 'Copenhagen', 'country': 'DK', 'latit...",Bycyklen,NaN,NaN,NaN,NaN
2,[Gobike A/S],/v2/networks/nu-connect,nu-connect,"{'city': 'Utrecht', 'country': 'NL', 'latitude...",Nu-Connect,NaN,NaN,NaN,NaN
3,[Urban Infrastructure Partner],/v2/networks/baerum-bysykkel,baerum-bysykkel,"{'city': 'Bærum', 'country': 'NO', 'latitude':...",Bysykkel,NaN,NaN,NaN,NaN
4,[Gobike A/S],/v2/networks/bysykkelen,bysykkelen,"{'city': 'Stavanger', 'country': 'NO', 'latitu...",Bysykkelen,NaN,NaN,NaN,NaN

In [ ]:
from pandas.io.json import json_normalize

citybikes_unpacked = json_normalize(json_dict['networks'],
                                    sep='_')
citybikes_unpacked.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  after removing the cwd from sys.path.

,company,href,id,name,location_city,location_country,location_latitude,location_longitude,source,gbfs_href,license_name,license_url,ebikes
0,[ЗАО «СитиБайк»],/v2/networks/velobike-moscow,velobike-moscow,Velobike,Moscow,RU,55.750000,37.616667,NaN,NaN,NaN,NaN,NaN
1,[Gobike A/S],/v2/networks/bycyklen,bycyklen,Bycyklen,Copenhagen,DK,55.673582,12.564984,NaN,NaN,NaN,NaN,NaN
2,[Gobike A/S],/v2/networks/nu-connect,nu-connect,Nu-Connect,Utrecht,NL,52.117000,5.067000,NaN,NaN,NaN,NaN,NaN
3,[Urban Infrastructure Partner],/v2/networks/baerum-bysykkel,baerum-bysykkel,Bysykkel,Bærum,NO,59.894550,10.546343,NaN,NaN,NaN,NaN,NaN
4,[Gobike A/S],/v2/networks/bysykkelen,bysykkelen,Bysykkelen,Stavanger,NO,58.969975,5.733107,NaN,NaN,NaN,NaN,NaN

In [ ]:
citybikes_unpacked.head()

,company,href,id,name,location_city,location_country,location_latitude,location_longitude,source,gbfs_href,license_name,license_url,ebikes
0,[ЗАО «СитиБайк»],/v2/networks/velobike-moscow,velobike-moscow,Velobike,Moscow,RU,55.750000,37.616667,NaN,NaN,NaN,NaN,NaN
1,[Gobike A/S],/v2/networks/bycyklen,bycyklen,Bycyklen,Copenhagen,DK,55.673582,12.564984,NaN,NaN,NaN,NaN,NaN
2,[Gobike A/S],/v2/networks/nu-connect,nu-connect,Nu-Connect,Utrecht,NL,52.117000,5.067000,NaN,NaN,NaN,NaN,NaN
3,[Urban Infrastructure Partner],/v2/networks/baerum-bysykkel,baerum-bysykkel,Bysykkel,Bærum,NO,59.894550,10.546343,NaN,NaN,NaN,NaN,NaN
4,[Gobike A/S],/v2/networks/bysykkelen,bysykkelen,Bysykkelen,Stavanger,NO,58.969975,5.733107,NaN,NaN,NaN,NaN,NaN

In [ ]:
citybikes_unpacked.to_json('out.json')
pd.read_json('out.json').head()

,company,href,id,name,location_city,location_country,location_latitude,location_longitude,source,gbfs_href,license_name,license_url,ebikes
0,[ЗАО «СитиБайк»],/v2/networks/velobike-moscow,velobike-moscow,Velobike,Moscow,RU,55.750000,37.616667,None,None,None,None,NaN
1,[Gobike A/S],/v2/networks/bycyklen,bycyklen,Bycyklen,Copenhagen,DK,55.673582,12.564984,None,None,None,None,NaN
2,[Gobike A/S],/v2/networks/nu-connect,nu-connect,Nu-Connect,Utrecht,NL,52.117000,5.067000,None,None,None,None,NaN
3,[Urban Infrastructure Partner],/v2/networks/baerum-bysykkel,baerum-bysykkel,Bysykkel,Bærum,NO,59.894550,10.546343,None,None,None,None,NaN
4,[Gobike A/S],/v2/networks/bysykkelen,bysykkelen,Bysykkelen,Stavanger,NO,58.969975,5.733107,None,None,None,None,NaN

In [ ]:
r = requests.get('https://httpbin.org/basic-auth/myuser/mypasswd')
r.status_code

401

In [ ]:
r = requests.get('https://httpbin.org/basic-auth/myuser/mypasswd',
                 auth=('myuser', 'mypasswd'))
r.status_code

200

In [ ]:
r.json()

{'authenticated': True, 'user': 'myuser'}

LESSON 16

In [ ]:
import numpy as np
import pandas as pd
import requests

req = requests.get('https://swapi.co/api/people/?format=json')

swapi_dict = req.json()

starwars_people_df = pd.DataFrame.from_dict(swapi_dict['results'])

blue_eyed_people_df = starwars_people_df.loc[starwars_people_df['eye_color'] == 'blue']

JSONDecodeError: ignored

LESSON 17

In [ ]:
!pip install lxml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (4.9.1)

In [ ]:
import pandas as pd

In [ ]:
html_string = """
<table>
    <thead>
      <tr>
        <th>Order date</th>
        <th>Region</th> 
        <th>Item</th>
        <th>Units</th>
        <th>Unit cost</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1/6/2018</td>
        <td>East</td> 
        <td>Pencil</td>
        <td>95</td>
        <td>1.99</td>
      </tr>
      <tr>
        <td>1/23/2018</td>
        <td>Central</td> 
        <td>Binder</td>
        <td>50</td>
        <td>19.99</td>
      </tr>
      <tr>
        <td>2/9/2018</td>
        <td>Central</td> 
        <td>Pencil</td>
        <td>36</td>
        <td>4.99</td>
      </tr>
      <tr>
        <td>3/15/2018</td>
        <td>West</td> 
        <td>Pen</td>
        <td>27</td>
        <td>19.99</td>
      </tr>
    </tbody>
</table>
"""

In [ ]:
dfs = pd.read_html(html_string)

len(dfs)

1

In [ ]:
df = dfs[0]

df

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

In [ ]:
df.shape

(4, 5)

In [ ]:
df.loc[df['Region'] == 'Central']

  Order date   Region    Item  Units  Unit cost
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99

In [ ]:
df.loc[df['Units'] > 35]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99

In [ ]:
html_string = """
<table>
  <tr>
    <td>Order date</td>
    <td>Region</td> 
    <td>Item</td>
    <td>Units</td>
    <td>Unit cost</td>
  </tr>
  <tr>
    <td>1/6/2018</td>
    <td>East</td> 
    <td>Pencil</td>
    <td>95</td>
    <td>1.99</td>
  </tr>
  <tr>
    <td>1/23/2018</td>
    <td>Central</td> 
    <td>Binder</td>
    <td>50</td>
    <td>19.99</td>
  </tr>
  <tr>
    <td>2/9/2018</td>
    <td>Central</td> 
    <td>Pencil</td>
    <td>36</td>
    <td>4.99</td>
  </tr>
  <tr>
    <td>3/15/2018</td>
    <td>West</td> 
    <td>Pen</td>
    <td>27</td>
    <td>19.99</td>
  </tr>
</table>
"""

In [ ]:
pd.read_html(html_string)[0]

            0        1       2      3          4
0  Order date   Region    Item  Units  Unit cost
1    1/6/2018     East  Pencil     95       1.99
2   1/23/2018  Central  Binder     50      19.99
3    2/9/2018  Central  Pencil     36       4.99
4   3/15/2018     West     Pen     27      19.99

In [ ]:
pd.read_html(html_string, header=0)[0]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

In [ ]:
html_url = "https://www.basketball-reference.com/leagues/NBA_2019_per_game.html"

nba_tables = pd.read_html(html_url)

len(nba_tables)

1

In [ ]:
nba = nba_tables[0]
nba.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9

In [ ]:
import requests

html_url = "https://en.wikipedia.org/wiki/The_Simpsons"

In [ ]:
r = requests.get(html_url)

wiki_tables = pd.read_html(r.text, header=0)
len(wiki_tables)

47

In [ ]:
simpsons = wiki_tables[1]
simpsons.head()

,Season,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
0,Season,Season,No. ofepisodes,Season premiere,Season finale,Time slot (ET),Avg. viewers(in millions),Most watched episode,Most watched episode
1,Season,Season,No. ofepisodes,Season premiere,Season finale,Time slot (ET),Avg. viewers(in millions),Viewers(millions),Episode title
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an 'F'"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,21.8,25.5,"""Colonel Homer"""

In [ ]:
simpsons.drop([0, 1], inplace=True)
simpsons.set_index('Season', inplace=True)
simpsons['No. ofepisodes'].unique()

array(['13', '22', '24', '25', '23', '21', '20'], dtype=object)

In [ ]:
simpsons = simpsons.loc[simpsons['No. ofepisodes'] != 'TBA']
min_season = simpsons['No. ofepisodes'].min()

min_season

'13'

In [ ]:
simpsons.loc[simpsons['No. ofepisodes'] == min_season]

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""

In [ ]:
simpsons.to_csv('out.csv')
pd.read_csv('out.csv', index_col='Season').head()

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an 'F'"""
3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,21.8,25.5,"""Colonel Homer"""
4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,22.4,28.6,"""Lisa's First Word"""
5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,18.9,24.0,"""Treehouse of Horror IV"""

LESSON 18

In [ ]:
import numpy as np
import pandas as pd
import requests

dfs = pd.read_html('fifa_players.html', encoding='utf-8')

fifa_df = dfs[0]

fifa_df = fifa_df.iloc[:, 2:-1]

most_hits_player = fifa_df.sort_values('Hits', ascending=False).head(1)

/usr/local/lib/python3.7/dist-packages/bs4/__init__.py:179: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")

ValueError: ignored

LESSON 19

In [ ]:
df = pd.DataFrame([[1,2,3], [4,5,6]],
                  columns=['A','B','C'])

df

   A  B  C
0  1  2  3
1  4  5  6

In [ ]:
df.to_pickle('out.pkl')

In [ ]:
!cat out.pkl

���      �pandas.core.frame��	DataFrame���)��}�(�_mgr��pandas.core.internals.managers��BlockManager����	functools��partial����pandas.core.internals.blocks��	new_block�����R�(h)}��ndim�KsNt�b�numpy.core.multiarray��_reconstruct����numpy��ndarray���K ��Cb���R�(KKK��h�dtype����i8�����R�(K�<�NNNJ����J����K t�b�C0                                          �t�b�builtins��slice���K KK��R���R���]�(�pandas.core.indexes.base��
_new_Index���h1�Index���}�(�data�hhK ��h��R�(KK��h �O8�����R�(K�|�NNNJ����J����K?t�b�]�(�A��B��C�et�b�name�Nu��R�h3�pandas.core.indexes.range��
RangeIndex���}�(hFN�start�K �stop�K�step�Ku��R�e��R��_typ��	dataframe��	_metadata�]��attrs�}��_flags�}��allows_duplicate_labels��sub.

In [ ]:
df = pd.read_pickle('out.pkl')
df

   A  B  C
0  1  2  3
1  4  5  6

In [ ]:
pip install PyQt4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement PyQt4 (from versions: none)
ERROR: No matching distribution found for PyQt4

In [ ]:
df = pd.read_clipboard()
df

PyperclipException: ignored

In [ ]:
df.to_clipboard()

PyperclipException: ignored

In [ ]:
!cat airline.sas7bdat

      �               �  0      H  �        D      �  \      t  4       @  4         4       �
  4       �
  4       p
  4       p
              p�@   @�l�?   ���?   �w��?    ף�?    ���? t�@   ����?    ף�?   `���?    �$�?    T��? x�@   ���?   ����?   �m4�?   �?5�?    V�? |�@    +�?   @�?   �K7�?   ����?   �I�? ��@   `�@   @
��?   ���?    ���?   @5^�? ��@   ��@   ज़�?   `���?   `���?    ���? ��@   @33@   �p�?   `���?   @�l�?    ���? ��@   ��~@   `ff�?   �Y�?   `�� @   ��v�? ��@    ��@   ���?    �u�?   @�z@   ����? ��@   ��@   @�A�?   ��|�?   ��@    �x�? ��@    �@@   �$�?   `��?   `�@   �n�? ��@   �=�@   ��C�?   ����?   ���@   ��S�? ��@   �K7@    X9�?   @io�?   �E�@    -��? ��@    )�@   �p�?   @���?    ��@   ���? ��@   ��L@   �=
�?   @6�?    �x	@   `���? ��@    �@   �&1�?    ���?   ��
@   ��S @ ��@   ��J@   �K7�?   ����?   ��K@   @���? ��@   �p="@   �I�?   ���?   `��@    V@ ��@   �$%@    ���?   �H.�?   ��K@   ���@ ��@   �=
*@   �l��?   @io�?   @
       ����                                      < 	       ����                                      (        ����                                               ����P                                                $                ����8               $      8      H      \      l            �����  �       Written by SAS  YEARyearY   level of output W   wage rate   R   interest rate   L   labor input K   capital input                          ���0                                                       ����            ����            ����            ����                ����                ����                ����                                                                                                                    ����       �����          0 ,                          .              ��������                                                                                                                                                    kIW-                                                             -                                                                                                                                    \                                        